
<?php
use Sulu\Component\Webspace\Manager\WebspaceCollection;
use Sulu\Component\Webspace\Portal;
use Sulu\Component\Webspace\Localization;
use Sulu\Component\Webspace\PortalInformation;
use Sulu\Component\Webspace\Theme;
use Sulu\Component\Webspace\Environment;
use Sulu\Component\Webspace\Security;
use Sulu\Component\Webspace\Segment;
use Sulu\Component\Webspace\Url;
use Sulu\Component\Webspace\Webspace;

/**
 * WebspaceCollectionCache
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Webspace component
 */
class WebspaceCollectionCache extends WebspaceCollection
{
    public function __construct()
    {
        $webspaceRefs = array();
        $portalRefs = array();
        $localizationRefs = array();
        $segmentRefs = array();
        $portalInformationRefs = array();

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu_io');
        $webspace->setName('Sulu CMF');
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('');
        $localization0->setShadow('auto');
        // parent id 0
        $localization1 = new Localization();
        $localization1->setLanguage('en');
        $localization1->setCountry('us');
        $localization1->setShadow('');
        $localization1->setParent($localization0);

        $localizationRefs['sulu_io_en_us'] = $localization1;

        $localization0->addChild($localization1);

        $localizationRefs['sulu_io_en'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('');
        $localization0->setShadow('');
        // parent id 0
        $localization1 = new Localization();
        $localization1->setLanguage('de');
        $localization1->setCountry('at');
        $localization1->setShadow('');
        $localization1->setParent($localization0);

        $localizationRefs['sulu_io_de_at'] = $localization1;

        $localization0->addChild($localization1);

        $localizationRefs['sulu_io_de'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $theme = new Theme();
        $theme->setKey('default');
        $theme->addExcludedTemplate('overview');
        $webspace->setTheme($theme);


        // new portal
        $portal = new Portal();
        $portal->setName('Sulu CMF AT');
        $portal->setKey('sulucmf_at');
        $portal->setResourceLocatorStrategy('tree');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('at');
        $portal->addLocalization($localization);


        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.at');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('www.sulu.at');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('sulu.at');
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('localhost');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('sulu-redirect.lo');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('sulu.lo');
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('test');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('localhost');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('sulu-redirect.lo');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('sulu.lo');
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulucmf_at'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu_io'] = $webspace;



        $portalInformationRefs['prod']['www.sulu.at'] = new PortalInformation(
            3,
            $webspaceRefs['sulu_io'],
            null,
            null,
            'www.sulu.at',
            null,
            'sulu.at'
        );

        $portalInformationRefs['prod']['sulu.at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.at',
            null,
            null
        );

        $portalInformationRefs['dev']['sulu-redirect.lo'] = new PortalInformation(
            3,
            $webspaceRefs['sulu_io'],
            null,
            null,
            'sulu-redirect.lo',
            null,
            'sulu.lo'
        );

        $portalInformationRefs['dev']['localhost'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'localhost',
            null,
            null
        );

        $portalInformationRefs['dev']['sulu.lo'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.lo',
            null,
            null
        );

        $portalInformationRefs['test']['sulu-redirect.lo'] = new PortalInformation(
            3,
            $webspaceRefs['sulu_io'],
            null,
            null,
            'sulu-redirect.lo',
            null,
            'sulu.lo'
        );

        $portalInformationRefs['test']['localhost'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'localhost',
            null,
            null
        );

        $portalInformationRefs['test']['sulu.lo'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.lo',
            null,
            null
        );


        $this->setWebspaces($webspaceRefs);
        $this->setPortals($portalRefs);
        $this->setPortalInformations($portalInformationRefs);
    }
}
