flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads'

when@test:
    flysystem:
        storages:
            default.storage:
                    adapter: 'memory'
