parameters:
    env(PHPCR_WORKSPACE): 'default'
    env(PHPCR_TRANSPORT): doctrinedbal
    env(PHPCR_BACKEND_URL): http://localhost:8080/server/
    env(PHPCR_USERNAME): admin
    env(PHPCR_PASSWORD): admin

sulu_document_manager:
    versioning:
        enabled: false # See https://docs.sulu.io/en/2.0/bundles/page/versioning.html if you want to enable versioning
    sessions:
        default:
            backend:
                type: '%env(PHPCR_TRANSPORT)%'
                url:  '%env(PHPCR_BACKEND_URL)%'
            workspace: '%env(PHPCR_WORKSPACE)%'
            username: '%env(PHPCR_USERNAME)%'
            password: '%env(PHPCR_PASSWORD)%'
        live:
            backend:
                type: '%env(PHPCR_TRANSPORT)%'
                url:  '%env(PHPCR_BACKEND_URL)%'
            workspace: '%env(PHPCR_WORKSPACE)%_live'
            username: '%env(PHPCR_USERNAME)%'
            password: '%env(PHPCR_PASSWORD)%'

when@prod: &prod
    sulu_document_manager:
        sessions:
            default:
                backend:
                    caches:
                        meta: doctrine_phpcr.meta_cache_provider
                        nodes: doctrine_phpcr.nodes_cache_provider
            live:
                backend:
                    caches:
                        meta: doctrine_phpcr.meta_cache_provider
                        nodes: doctrine_phpcr.nodes_cache_provider

    services:
        doctrine_phpcr.meta_cache_provider:
            class: Symfony\Component\Cache\Psr16Cache
            public: false
            arguments:
                - '@doctrine_phpcr.meta_cache_pool'
            tags:
                - { name: 'kernel.reset', method: 'reset' }

        doctrine_phpcr.nodes_cache_provider:
            class: Symfony\Component\Cache\Psr16Cache
            public: false
            arguments:
                - '@doctrine_phpcr.nodes_cache_pool'
            tags:
                - { name: 'kernel.reset', method: 'reset' }

    framework:
        cache:
            pools:
                doctrine_phpcr.meta_cache_pool:
                    adapter: cache.app

                doctrine_phpcr.nodes_cache_pool:
                    adapter: cache.app

when@stage: *prod
