<?php
/*
 * This file is part of the Sulu CMS.
 *
 * (c) MASSIVE ART WebServices GmbH
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Sulu\Bundle\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{
    /**
     * Get Collection by id
     * @param $id
     * @param bool $asArray
     * @return mixed|null
     */
    public function findCollectionById($id, $asArray = false)
    {
        try {
            $qb = $this->createQueryBuilder('collection')
                ->leftJoin('collection.meta', 'collectionMeta')
                ->leftJoin('collection.type', 'type')
                ->leftJoin('collection.parent', 'parent')
                ->leftJoin('collection.children', 'children')
                ->leftJoin('children.media', 'childrenMedia')
                ->leftJoin('collection.media', 'media')

                /* TODO TestUser has no Contact!
                ->leftJoin('collection.creator', 'creator')
                ->leftJoin('creator.contact', 'creatorContact')
                ->leftJoin('collection.changer', 'changer')
                ->leftJoin('changer.contact', 'changerContact')
                */

                ->addSelect('collection')
                ->addSelect('collectionMeta')
                ->addSelect('type')
                ->addSelect('parent')
                ->addSelect('children')
                ->addSelect('childrenMedia')

                /* TODO TestUser has no Contact!
                ->addSelect('creator')
                ->addSelect('changer')
                ->addSelect('creatorContact')
                ->addSelect('changerContact')
                */
                ->addSelect('media')
                ->where('collection.id = :collectionId');

            $query = $qb->getQuery();
            $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
            $query->setParameter('collectionId', $id);

            if ($asArray) {
                if (isset($query->getArrayResult()[0])) {
                    return $query->getArrayResult()[0];
                } else {
                    return null;
                }
            } else {
                return $query->getSingleResult();
            }
        } catch (NoResultException $ex) {
            return null;
        }
    }

    /**
     * Give back all Collections from specific parentId
     * @param null $parentId
     * @param null $depth
     * @return array|null
     */
    public function findCollections($parentId = null, $depth = null)
    {
        try {
            $qb = $this->createQueryBuilder('collection')
                ->leftJoin('collection.meta', 'collectionMeta')
                ->leftJoin('collection.type', 'type')
                ->leftJoin('collection.parent', 'parent')
                ->leftJoin('collection.children', 'children')
                ->leftJoin('children.media', 'childrenMedia')
                ->leftJoin('collection.media', 'media')
                /*
                ->leftJoin('collection.creator', 'creator')
                ->leftJoin('creator.contact', 'creatorContact')
                ->leftJoin('collection.changer', 'changer')
                ->leftJoin('changer.contact', 'changerContact')
                */
                ->addSelect('collectionMeta')
                ->addSelect('type')
                ->addSelect('parent')
                ->addSelect('children')
                ->addSelect('childrenMedia')
                /*
                ->addSelect('creator')
                ->addSelect('changer')
                ->addSelect('creatorContact')
                ->addSelect('changerContact')
                */
                ->addSelect('media');

            if ($parentId !== null) {
                $qb->where('parent.id = :parentId');
            }
            if ($depth !== null) {
                $qb->where('collection.depth = :depth');
            }

            $query = $qb->getQuery();
            $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
            if ($parentId !== null) {
                $query->setParameter('parentId', $parentId);
            }
            if ($depth !== null) {
                $query->setParameter('depth', $depth);
            }

            return $query->getArrayResult();
        } catch (NoResultException $ex) {
            return null;
        }
    }

    /**
     * finds all Collections but only selects given fields
     * @param array $fields
     * @return array
     */
    public function findAllSelect($fields = array())
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->from($this->getEntityName(), 'collection');

        foreach ($fields as $field) {
            $qb->addSelect('collection.' . $field . ' AS ' . $field);
        }

        $query = $qb->getQuery();
        $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);

        return $query->getArrayResult();
    }

    /**
     * Get Collection by id to delete
     * @param $id
     * @return mixed
     */
    public function findCollectionByIdForDelete($id)
    {
        try {
            $qb = $this->createQueryBuilder('collection')
                ->leftJoin('collection.media', 'media')
                ->addSelect('media')
                ->where('collection.id = :collectionId');

            $query = $qb->getQuery();
            $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
            $query->setParameter('collectionId', $id);

            return $query->getSingleResult();
        } catch (NoResultException $ex) {
            return null;
        }
    }
}
