<?php

namespace Sulu\Bundle\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * FilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionGroupRepository extends EntityRepository implements ConditionGroupRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function findById($id)
    {
        try {
            $queryBuilder = $this->createQueryBuilder('conditionGroup')
                ->andWhere('conditionGroup.id = :conditionGroupId')
                ->addSelect('conditions')
                ->leftJoin('conditionGroup.conditions', 'conditions')
                ->setParameter('conditionGroupId', $id);
            return $queryBuilder->getQuery()->getSingleResult();
        } catch (NoResultException $exc) {
            return null;
        }
    }
}
