framework:
    secret: secret
    router: { resource: '%kernel.project_dir%/config/routing.yml' }
    test: ~
    profiler:
        enabled: false
    mailer:
        dsn: 'null://null'
        message_bus: false # else messenger component duplicates the message: https://github.com/symfony/symfony/issues/48004#issuecomment-2476617713

    lock: 'flock://%kernel.project_dir%/var/lock'

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
    dbal:
        url: '%env(DATABASE_URL)%'

jms_serializer:
    metadata:
        debug: '%kernel.debug%'

flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads'

sulu_admin:
    name: SULU 2.0
    email: installation.email@sulu.test

sulu_security:
    checker:
        enabled: true

sulu_test:
    enable_test_user_provider: true
