<?php

namespace Proxies\__CG__\Sulu\Bundle\ContactBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contact extends \Sulu\Bundle\ContactBundle\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setMiddleName($middleName)
    {
        $this->__load();
        return parent::setMiddleName($middleName);
    }

    public function getMiddleName()
    {
        $this->__load();
        return parent::getMiddleName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function getFullName()
    {
        $this->__load();
        return parent::getFullName();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function setCurrentPosition($position)
    {
        $this->__load();
        return parent::setCurrentPosition($position);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setBirthday($birthday)
    {
        $this->__load();
        return parent::setBirthday($birthday);
    }

    public function getBirthday()
    {
        $this->__load();
        return parent::getBirthday();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setChanged($changed)
    {
        $this->__load();
        return parent::setChanged($changed);
    }

    public function getChanged()
    {
        $this->__load();
        return parent::getChanged();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function addLocale(\Sulu\Bundle\ContactBundle\Entity\ContactLocale $locales)
    {
        $this->__load();
        return parent::addLocale($locales);
    }

    public function removeLocale(\Sulu\Bundle\ContactBundle\Entity\ContactLocale $locales)
    {
        $this->__load();
        return parent::removeLocale($locales);
    }

    public function getLocales()
    {
        $this->__load();
        return parent::getLocales();
    }

    public function addActivitie(\Sulu\Bundle\ContactBundle\Entity\Activity $activities)
    {
        $this->__load();
        return parent::addActivitie($activities);
    }

    public function removeActivitie(\Sulu\Bundle\ContactBundle\Entity\Activity $activities)
    {
        $this->__load();
        return parent::removeActivitie($activities);
    }

    public function getActivities()
    {
        $this->__load();
        return parent::getActivities();
    }

    public function setChanger(\Sulu\Component\Security\UserInterface $changer = NULL)
    {
        $this->__load();
        return parent::setChanger($changer);
    }

    public function getChanger()
    {
        $this->__load();
        return parent::getChanger();
    }

    public function setCreator(\Sulu\Component\Security\UserInterface $creator = NULL)
    {
        $this->__load();
        return parent::setCreator($creator);
    }

    public function getCreator()
    {
        $this->__load();
        return parent::getCreator();
    }

    public function addNote(\Sulu\Bundle\ContactBundle\Entity\Note $notes)
    {
        $this->__load();
        return parent::addNote($notes);
    }

    public function removeNote(\Sulu\Bundle\ContactBundle\Entity\Note $notes)
    {
        $this->__load();
        return parent::removeNote($notes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function addEmail(\Sulu\Bundle\ContactBundle\Entity\Email $emails)
    {
        $this->__load();
        return parent::addEmail($emails);
    }

    public function removeEmail(\Sulu\Bundle\ContactBundle\Entity\Email $emails)
    {
        $this->__load();
        return parent::removeEmail($emails);
    }

    public function getEmails()
    {
        $this->__load();
        return parent::getEmails();
    }

    public function addPhone(\Sulu\Bundle\ContactBundle\Entity\Phone $phones)
    {
        $this->__load();
        return parent::addPhone($phones);
    }

    public function removePhone(\Sulu\Bundle\ContactBundle\Entity\Phone $phones)
    {
        $this->__load();
        return parent::removePhone($phones);
    }

    public function getPhones()
    {
        $this->__load();
        return parent::getPhones();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function addFax(\Sulu\Bundle\ContactBundle\Entity\Fax $faxes)
    {
        $this->__load();
        return parent::addFax($faxes);
    }

    public function removeFax(\Sulu\Bundle\ContactBundle\Entity\Fax $faxes)
    {
        $this->__load();
        return parent::removeFax($faxes);
    }

    public function getFaxes()
    {
        $this->__load();
        return parent::getFaxes();
    }

    public function addUrl(\Sulu\Bundle\ContactBundle\Entity\Url $urls)
    {
        $this->__load();
        return parent::addUrl($urls);
    }

    public function removeUrl(\Sulu\Bundle\ContactBundle\Entity\Url $urls)
    {
        $this->__load();
        return parent::removeUrl($urls);
    }

    public function getUrls()
    {
        $this->__load();
        return parent::getUrls();
    }

    public function addFaxe(\Sulu\Bundle\ContactBundle\Entity\Fax $faxes)
    {
        $this->__load();
        return parent::addFaxe($faxes);
    }

    public function removeFaxe(\Sulu\Bundle\ContactBundle\Entity\Fax $faxes)
    {
        $this->__load();
        return parent::removeFaxe($faxes);
    }

    public function setFormOfAddress($formOfAddress)
    {
        $this->__load();
        return parent::setFormOfAddress($formOfAddress);
    }

    public function addTag(\Sulu\Bundle\TagBundle\Entity\Tag $tags)
    {
        $this->__load();
        return parent::addTag($tags);
    }

    public function getFormOfAddress()
    {
        $this->__load();
        return parent::getFormOfAddress();
    }

    public function setSalutation($salutation)
    {
        $this->__load();
        return parent::setSalutation($salutation);
    }

    public function getSalutation()
    {
        $this->__load();
        return parent::getSalutation();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function removeTag(\Sulu\Bundle\TagBundle\Entity\Tag $tags)
    {
        $this->__load();
        return parent::removeTag($tags);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function getTagNameArray()
    {
        $this->__load();
        return parent::getTagNameArray();
    }

    public function addAccountContact(\Sulu\Bundle\ContactBundle\Entity\AccountContact $accountContacts)
    {
        $this->__load();
        return parent::addAccountContact($accountContacts);
    }

    public function removeAccountContact(\Sulu\Bundle\ContactBundle\Entity\AccountContact $accountContacts)
    {
        $this->__load();
        return parent::removeAccountContact($accountContacts);
    }

    public function getAccountContacts()
    {
        $this->__load();
        return parent::getAccountContacts();
    }

    public function setNewsletter($newsletter)
    {
        $this->__load();
        return parent::setNewsletter($newsletter);
    }

    public function getNewsletter()
    {
        $this->__load();
        return parent::getNewsletter();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function getMainAccount()
    {
        $this->__load();
        return parent::getMainAccount();
    }

    public function getAddresses()
    {
        $this->__load();
        return parent::getAddresses();
    }

    public function setMainEmail($mainEmail)
    {
        $this->__load();
        return parent::setMainEmail($mainEmail);
    }

    public function getMainEmail()
    {
        $this->__load();
        return parent::getMainEmail();
    }

    public function setMainPhone($mainPhone)
    {
        $this->__load();
        return parent::setMainPhone($mainPhone);
    }

    public function getMainPhone()
    {
        $this->__load();
        return parent::getMainPhone();
    }

    public function setMainFax($mainFax)
    {
        $this->__load();
        return parent::setMainFax($mainFax);
    }

    public function getMainFax()
    {
        $this->__load();
        return parent::getMainFax();
    }

    public function setMainUrl($mainUrl)
    {
        $this->__load();
        return parent::setMainUrl($mainUrl);
    }

    public function getMainUrl()
    {
        $this->__load();
        return parent::getMainUrl();
    }

    public function addContactAddresse(\Sulu\Bundle\ContactBundle\Entity\ContactAddress $contactAddresses)
    {
        $this->__load();
        return parent::addContactAddresse($contactAddresses);
    }

    public function removeContactAddresse(\Sulu\Bundle\ContactBundle\Entity\ContactAddress $contactAddresses)
    {
        $this->__load();
        return parent::removeContactAddresse($contactAddresses);
    }

    public function getContactAddresses()
    {
        $this->__load();
        return parent::getContactAddresses();
    }

    public function addAssignedActivitie(\Sulu\Bundle\ContactBundle\Entity\Activity $assignedActivities)
    {
        $this->__load();
        return parent::addAssignedActivitie($assignedActivities);
    }

    public function removeAssignedActivitie(\Sulu\Bundle\ContactBundle\Entity\Activity $assignedActivities)
    {
        $this->__load();
        return parent::removeAssignedActivitie($assignedActivities);
    }

    public function getAssignedActivities()
    {
        $this->__load();
        return parent::getAssignedActivities();
    }

    public function getMainAddress()
    {
        $this->__load();
        return parent::getMainAddress();
    }

    public function addMedia(\Sulu\Bundle\MediaBundle\Entity\Media $medias)
    {
        $this->__load();
        return parent::addMedia($medias);
    }

    public function addCategorie(\Sulu\Bundle\CategoryBundle\Entity\Category $categories)
    {
        $this->__load();
        return parent::addCategorie($categories);
    }

    public function removeMedia(\Sulu\Bundle\MediaBundle\Entity\Media $medias)
    {
        $this->__load();
        return parent::removeMedia($medias);
    }

    public function getMedias()
    {
        $this->__load();
        return parent::getMedias();
    }

    public function removeCategorie(\Sulu\Bundle\CategoryBundle\Entity\Category $categories)
    {
        $this->__load();
        return parent::removeCategorie($categories);
    }

    public function getCategories()
    {
        $this->__load();
        return parent::getCategories();
    }

    public function getLinks()
    {
        $this->__load();
        return parent::getLinks();
    }

    public function createSelfLink()
    {
        $this->__load();
        return parent::createSelfLink();
    }

    public function getApiPath()
    {
        $this->__load();
        return parent::getApiPath();
    }

    public function hasApiPath()
    {
        $this->__load();
        return parent::hasApiPath();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'firstName', 'middleName', 'lastName', 'birthday', 'created', 'changed', 'salutation', 'formOfAddress', 'disabled', 'newsletter', 'gender', 'mainEmail', 'mainPhone', 'mainFax', 'mainUrl', 'id', 'locales', 'activities', 'assignedActivities', 'contactAddresses', 'accountContacts', 'title', 'medias', 'categories', 'urls', 'notes', 'emails', 'phones', 'faxes', 'tags', 'changer', 'creator');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}