<?php

namespace Proxies\__CG__\Sulu\Bundle\SecurityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Role extends \Sulu\Bundle\SecurityBundle\Entity\Role implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addPermission(\Sulu\Bundle\SecurityBundle\Entity\Permission $permissions)
    {
        $this->__load();
        return parent::addPermission($permissions);
    }

    public function removePermission(\Sulu\Bundle\SecurityBundle\Entity\Permission $permissions)
    {
        $this->__load();
        return parent::removePermission($permissions);
    }

    public function getPermissions()
    {
        $this->__load();
        return parent::getPermissions();
    }

    public function addUserRole(\Sulu\Bundle\SecurityBundle\Entity\UserRole $userRoles)
    {
        $this->__load();
        return parent::addUserRole($userRoles);
    }

    public function removeUserRole(\Sulu\Bundle\SecurityBundle\Entity\UserRole $userRoles)
    {
        $this->__load();
        return parent::removeUserRole($userRoles);
    }

    public function getUserRoles()
    {
        $this->__load();
        return parent::getUserRoles();
    }

    public function addGroup(\Sulu\Bundle\SecurityBundle\Entity\Group $groups)
    {
        $this->__load();
        return parent::addGroup($groups);
    }

    public function removeGroup(\Sulu\Bundle\SecurityBundle\Entity\Group $groups)
    {
        $this->__load();
        return parent::removeGroup($groups);
    }

    public function getGroups()
    {
        $this->__load();
        return parent::getGroups();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setSystem($system)
    {
        $this->__load();
        return parent::setSystem($system);
    }

    public function getSystem()
    {
        $this->__load();
        return parent::getSystem();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setChanged($changed)
    {
        $this->__load();
        return parent::setChanged($changed);
    }

    public function getChanged()
    {
        $this->__load();
        return parent::getChanged();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setChanger(\Sulu\Bundle\SecurityBundle\Entity\User $changer = NULL)
    {
        $this->__load();
        return parent::setChanger($changer);
    }

    public function getChanger()
    {
        $this->__load();
        return parent::getChanger();
    }

    public function setCreator(\Sulu\Bundle\SecurityBundle\Entity\User $creator = NULL)
    {
        $this->__load();
        return parent::setCreator($creator);
    }

    public function getCreator()
    {
        $this->__load();
        return parent::getCreator();
    }

    public function setSecurityType(\Sulu\Bundle\SecurityBundle\Entity\SecurityType $securityType = NULL)
    {
        $this->__load();
        return parent::setSecurityType($securityType);
    }

    public function getSecurityType()
    {
        $this->__load();
        return parent::getSecurityType();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'system', 'created', 'changed', 'id', 'changer', 'creator', 'securityType', 'permissions', 'userRoles', 'groups');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}