<?php

declare(strict_types=1);

namespace Sulu\Bundle\MigrationBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221122205425 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->skipIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\MariaDb1027Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\MariaDb1027Platform'."
        );

        $this->addSql('CREATE TABLE ac_activities (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(191) NOT NULL, context LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', timestamp DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', batch VARCHAR(191) DEFAULT NULL, payload LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, resourceLocale VARCHAR(191) DEFAULT NULL, resourceWebspaceKey VARCHAR(191) DEFAULT NULL, resourceTitle VARCHAR(191) DEFAULT NULL, resourceTitleLocale VARCHAR(191) DEFAULT NULL, resourceSecurityContext VARCHAR(191) DEFAULT NULL, resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, userId INT DEFAULT NULL, INDEX IDX_3EE015D064B64DCC (userId), INDEX timestamp_idx (timestamp), INDEX resourceKey_idx (resourceKey), INDEX resourceId_idx (resourceId), INDEX resourceSecurityContext_idx (resourceSecurityContext), INDEX resourceSecurityObjectType_idx (resourceSecurityObjectType), INDEX resourceSecurityObjectId_idx (resourceSecurityObjectId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE at_target_group_conditions (id INT AUTO_INCREMENT NOT NULL, `type` VARCHAR(255) NOT NULL, `condition` LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', idTargetGroupRules INT DEFAULT NULL, INDEX IDX_94078B9989EB12AB (idTargetGroupRules), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE at_target_group_rules (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, frequency INT NOT NULL, idTargetGroups INT DEFAULT NULL, INDEX IDX_189AEDAD9FCCEF27 (idTargetGroups), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE at_target_group_webspaces (id INT AUTO_INCREMENT NOT NULL, webspaceKey VARCHAR(255) NOT NULL, idTargetGroups INT DEFAULT NULL, INDEX IDX_4B0C69E59FCCEF27 (idTargetGroups), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE at_target_groups (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, priority INT NOT NULL, allWebspaces TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ca_categories (id INT AUTO_INCREMENT NOT NULL, category_key VARCHAR(191) DEFAULT NULL, default_locale VARCHAR(5) NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idCategoriesParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_3D85D789AF5206F3 (category_key), INDEX IDX_3D85D78937A3C3B1 (idCategoriesParent), INDEX IDX_3D85D789DBF11E1D (idUsersCreator), INDEX IDX_3D85D78930D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ca_category_meta (id INT AUTO_INCREMENT NOT NULL, meta_key VARCHAR(45) NOT NULL, value VARCHAR(255) NOT NULL, locale VARCHAR(5) DEFAULT NULL, idCategories INT NOT NULL, INDEX IDX_2575BBB0B8075882 (idCategories), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ca_category_translation_medias (id INT AUTO_INCREMENT NOT NULL, position INT DEFAULT 0 NOT NULL, idCategoryTranslations INT NOT NULL, idMedia INT NOT NULL, INDEX IDX_39FC41BA17CA14DA (idCategoryTranslations), INDEX IDX_39FC41BA7DE8E211 (idMedia), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ca_category_translations (id INT AUTO_INCREMENT NOT NULL, translation VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idCategories INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_5DCED5E3B8075882 (idCategories), INDEX IDX_5DCED5E3DBF11E1D (idUsersCreator), INDEX IDX_5DCED5E330D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ca_keywords (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(5) NOT NULL, keyword VARCHAR(191) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_FE02CA0BDBF11E1D (idUsersCreator), INDEX IDX_FE02CA0B30D07CD5 (idUsersChanger), INDEX IDX_FE02CA0B5A93713B (keyword), UNIQUE INDEX unique_idx (keyword, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ca_category_translation_keywords (idKeywords INT NOT NULL, idCategoryTranslations INT NOT NULL, INDEX IDX_D15FBE37F9FC9F05 (idKeywords), INDEX IDX_D15FBE3717CA14DA (idCategoryTranslations), PRIMARY KEY(idKeywords, idCategoryTranslations)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_addresses (id INT AUTO_INCREMENT NOT NULL, main TINYINT(1) NOT NULL, idAddresses INT NOT NULL, idAccounts INT NOT NULL, INDEX IDX_4165FE4893205E40 (idAddresses), INDEX IDX_4165FE48996BB4F7 (idAccounts), UNIQUE INDEX UNIQ_4165FE4893205E40996BB4F7 (idAddresses, idAccounts), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_contacts (id INT AUTO_INCREMENT NOT NULL, main TINYINT(1) NOT NULL, idPositions INT DEFAULT NULL, idContacts INT NOT NULL, idAccounts INT NOT NULL, INDEX IDX_28C6CA0E2A75CE2A (idPositions), INDEX IDX_28C6CA0E60E33F28 (idContacts), INDEX IDX_28C6CA0E996BB4F7 (idAccounts), UNIQUE INDEX UNIQ_28C6CA0E60E33F28996BB4F7 (idContacts, idAccounts), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_accounts (id INT AUTO_INCREMENT NOT NULL, logo INT DEFAULT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, name VARCHAR(150) NOT NULL, externalId VARCHAR(255) DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, corporation VARCHAR(255) DEFAULT NULL, note LONGTEXT DEFAULT NULL, uid VARCHAR(50) DEFAULT NULL, registerNumber VARCHAR(255) DEFAULT NULL, placeOfJurisdiction VARCHAR(255) DEFAULT NULL, mainEmail VARCHAR(255) DEFAULT NULL, mainPhone VARCHAR(255) DEFAULT NULL, mainFax VARCHAR(255) DEFAULT NULL, mainUrl VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idContactsMain INT DEFAULT NULL, idAccountsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_805CD14A6D4A8651 (idContactsMain), INDEX IDX_805CD14AC9171171 (idAccountsParent), INDEX IDX_805CD14AE48E9A13 (logo), INDEX IDX_805CD14ADBF11E1D (idUsersCreator), INDEX IDX_805CD14A30D07CD5 (idUsersChanger), INDEX IDX_805CD14A5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_urls (idAccounts INT NOT NULL, idUrls INT NOT NULL, INDEX IDX_ADF18382996BB4F7 (idAccounts), INDEX IDX_ADF183825969693F (idUrls), PRIMARY KEY(idAccounts, idUrls)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_phones (idAccounts INT NOT NULL, idPhones INT NOT NULL, INDEX IDX_918DA964996BB4F7 (idAccounts), INDEX IDX_918DA9648039866F (idPhones), PRIMARY KEY(idAccounts, idPhones)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_emails (idAccounts INT NOT NULL, idEmails INT NOT NULL, INDEX IDX_3E246FC3996BB4F7 (idAccounts), INDEX IDX_3E246FC32F9040C8 (idEmails), PRIMARY KEY(idAccounts, idEmails)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_notes (idAccounts INT NOT NULL, idNotes INT NOT NULL, INDEX IDX_A3FBB24A996BB4F7 (idAccounts), INDEX IDX_A3FBB24A16DFE591 (idNotes), PRIMARY KEY(idAccounts, idNotes)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_faxes (idAccounts INT NOT NULL, idFaxes INT NOT NULL, INDEX IDX_7A4E77DC996BB4F7 (idAccounts), INDEX IDX_7A4E77DCCF6A2007 (idFaxes), PRIMARY KEY(idAccounts, idFaxes)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_social_media_profiles (idAccounts INT NOT NULL, idSocialMediaProfiles INT NOT NULL, INDEX IDX_E06F75F5996BB4F7 (idAccounts), INDEX IDX_E06F75F5573F8344 (idSocialMediaProfiles), PRIMARY KEY(idAccounts, idSocialMediaProfiles)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_bank_accounts (idAccounts INT NOT NULL, idBankAccounts INT NOT NULL, INDEX IDX_C873A532996BB4F7 (idAccounts), INDEX IDX_C873A53237FCD1D8 (idBankAccounts), PRIMARY KEY(idAccounts, idBankAccounts)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_categories (idAccounts INT NOT NULL, idCategories INT NOT NULL, INDEX IDX_B60E9510996BB4F7 (idAccounts), INDEX IDX_B60E9510B8075882 (idCategories), PRIMARY KEY(idAccounts, idCategories)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_medias (idAccounts INT NOT NULL, idMedias INT NOT NULL, INDEX IDX_60772810996BB4F7 (idAccounts), INDEX IDX_6077281071C3071B (idMedias), PRIMARY KEY(idAccounts, idMedias)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_account_tags (idAccounts INT NOT NULL, idTags INT NOT NULL, INDEX IDX_E8D92005996BB4F7 (idAccounts), INDEX IDX_E8D920051C41CAB8 (idTags), PRIMARY KEY(idAccounts, idTags)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_address_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_addresses (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(250) DEFAULT NULL, primaryAddress TINYINT(1) DEFAULT NULL, deliveryAddress TINYINT(1) DEFAULT NULL, billingAddress TINYINT(1) DEFAULT NULL, street VARCHAR(150) DEFAULT NULL, number VARCHAR(60) DEFAULT NULL, addition VARCHAR(60) DEFAULT NULL, zip VARCHAR(60) DEFAULT NULL, city VARCHAR(60) DEFAULT NULL, state VARCHAR(60) DEFAULT NULL, countryCode VARCHAR(5) DEFAULT NULL, postboxNumber VARCHAR(100) DEFAULT NULL, postboxPostcode VARCHAR(100) DEFAULT NULL, postboxCity VARCHAR(100) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, note LONGTEXT DEFAULT NULL, idAdressTypes INT NOT NULL, INDEX IDX_26E9A6142A37021A (idAdressTypes), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_bank_account (id INT AUTO_INCREMENT NOT NULL, bankName VARCHAR(150) DEFAULT NULL, bic VARCHAR(100) DEFAULT NULL, iban VARCHAR(100) NOT NULL, public TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_addresses (id INT AUTO_INCREMENT NOT NULL, main TINYINT(1) NOT NULL, idAddresses INT NOT NULL, idContacts INT NOT NULL, INDEX IDX_DEE056893205E40 (idAddresses), INDEX IDX_DEE056860E33F28 (idContacts), UNIQUE INDEX UNIQ_DEE056893205E4060E33F28 (idAddresses, idContacts), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_locales (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(60) NOT NULL, idContacts INT NOT NULL, INDEX IDX_31E5672760E33F28 (idContacts), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_titles (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(60) NOT NULL, UNIQUE INDEX UNIQ_4463FC02B36786B (title), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contacts (id INT AUTO_INCREMENT NOT NULL, avatar INT DEFAULT NULL, firstName VARCHAR(60) NOT NULL, middleName VARCHAR(60) DEFAULT NULL, lastName VARCHAR(60) NOT NULL, birthday DATE DEFAULT NULL, salutation VARCHAR(255) DEFAULT NULL, formOfAddress INT DEFAULT NULL, newsletter TINYINT(1) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, note LONGTEXT DEFAULT NULL, mainEmail VARCHAR(255) DEFAULT NULL, mainPhone VARCHAR(255) DEFAULT NULL, mainFax VARCHAR(255) DEFAULT NULL, mainUrl VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idTitles INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_79D45A95A254E939 (idTitles), INDEX IDX_79D45A951677722F (avatar), INDEX IDX_79D45A95DBF11E1D (idUsersCreator), INDEX IDX_79D45A9530D07CD5 (idUsersChanger), INDEX IDX_79D45A952392A156 (firstName), INDEX IDX_79D45A9591161A88 (lastName), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_urls (idContacts INT NOT NULL, idUrls INT NOT NULL, INDEX IDX_99D86D760E33F28 (idContacts), INDEX IDX_99D86D75969693F (idUrls), PRIMARY KEY(idContacts, idUrls)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_notes (idContacts INT NOT NULL, idNotes INT NOT NULL, INDEX IDX_B85E7B3460E33F28 (idContacts), INDEX IDX_B85E7B3416DFE591 (idNotes), PRIMARY KEY(idContacts, idNotes)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_emails (idContacts INT NOT NULL, idEmails INT NOT NULL, INDEX IDX_8982963160E33F28 (idContacts), INDEX IDX_898296312F9040C8 (idEmails), PRIMARY KEY(idContacts, idEmails)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_phones (idContacts INT NOT NULL, idPhones INT NOT NULL, INDEX IDX_262B509660E33F28 (idContacts), INDEX IDX_262B50968039866F (idPhones), PRIMARY KEY(idContacts, idPhones)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_faxes (idContacts INT NOT NULL, idFaxes INT NOT NULL, INDEX IDX_61EBBEA260E33F28 (idContacts), INDEX IDX_61EBBEA2CF6A2007 (idFaxes), PRIMARY KEY(idContacts, idFaxes)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_social_media_profiles (idContacts INT NOT NULL, idSocialMediaProfiles INT NOT NULL, INDEX IDX_74FF4CC060E33F28 (idContacts), INDEX IDX_74FF4CC0573F8344 (idSocialMediaProfiles), PRIMARY KEY(idContacts, idSocialMediaProfiles)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_bank_accounts (idContacts INT NOT NULL, idBankAccounts INT NOT NULL, INDEX IDX_76CDDA0660E33F28 (idContacts), INDEX IDX_76CDDA0637FCD1D8 (idBankAccounts), PRIMARY KEY(idContacts, idBankAccounts)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_medias (idContacts INT NOT NULL, idMedias INT NOT NULL, INDEX IDX_D7D1D1E260E33F28 (idContacts), INDEX IDX_D7D1D1E271C3071B (idMedias), PRIMARY KEY(idContacts, idMedias)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_categories (idContacts INT NOT NULL, idCategories INT NOT NULL, INDEX IDX_8D2C3E2360E33F28 (idContacts), INDEX IDX_8D2C3E23B8075882 (idCategories), PRIMARY KEY(idContacts, idCategories)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_contact_tags (idContacts INT NOT NULL, idTags INT NOT NULL, INDEX IDX_4CB5255060E33F28 (idContacts), INDEX IDX_4CB525501C41CAB8 (idTags), PRIMARY KEY(idContacts, idTags)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_email_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_emails (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(60) NOT NULL, idEmailTypes INT NOT NULL, INDEX IDX_A2F2CB77D816E840 (idEmailTypes), INDEX IDX_A2F2CB77E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_fax_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_faxes (id INT AUTO_INCREMENT NOT NULL, fax VARCHAR(255) NOT NULL, idFaxTypes INT NOT NULL, INDEX IDX_A5EC6A18B466C5DA (idFaxTypes), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_notes (id INT AUTO_INCREMENT NOT NULL, value LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_phone_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_phones (id INT AUTO_INCREMENT NOT NULL, phone VARCHAR(60) NOT NULL, idPhoneTypes INT NOT NULL, INDEX IDX_D5B0DD0A4249AD7 (idPhoneTypes), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_positions (id INT AUTO_INCREMENT NOT NULL, position VARCHAR(191) NOT NULL, UNIQUE INDEX UNIQ_9FBC367E462CE4F5 (position), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_social_media_profile_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_social_media_profiles (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, idSocialMediaTypes INT NOT NULL, INDEX IDX_DF585BFBB5BEA95F (idSocialMediaTypes), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_url_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE co_urls (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(255) NOT NULL, idUrlTypes INT NOT NULL, INDEX IDX_6F03842E882335CC (idUrlTypes), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_collection_meta (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(191) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, idCollections INT NOT NULL, INDEX IDX_F8D5E71693782C96 (idCollections), INDEX IDX_F8D5E7162B36786B (title), INDEX IDX_F8D5E7164180C698 (locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_collection_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, collection_type_key VARCHAR(191) DEFAULT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_FB78DFB179078378 (collection_type_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_collections (id INT AUTO_INCREMENT NOT NULL, style VARCHAR(255) DEFAULT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, collection_key VARCHAR(191) DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idCollectionsMetaDefault INT DEFAULT NULL, idCollectionTypes INT NOT NULL, idCollectionsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_F0D4887221904CD (collection_key), UNIQUE INDEX UNIQ_F0D4887CFA3F467 (idCollectionsMetaDefault), INDEX IDX_F0D4887E67924D6 (idCollectionTypes), INDEX IDX_F0D4887A4F2DCF8 (idCollectionsParent), INDEX IDX_F0D4887DBF11E1D (idUsersCreator), INDEX IDX_F0D488730D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_version_content_languages (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(5) NOT NULL, idFileVersions INT DEFAULT NULL, INDEX IDX_F3FD652C911ADE33 (idFileVersions), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_version_meta (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(191) NOT NULL, description LONGTEXT DEFAULT NULL, copyright LONGTEXT DEFAULT NULL, credits LONGTEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, idFileVersions INT NOT NULL, INDEX IDX_AD44B0AD911ADE33 (idFileVersions), INDEX IDX_AD44B0AD2B36786B (title), INDEX IDX_AD44B0AD4180C698 (locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_version_publish_languages (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(5) NOT NULL, idFileVersions INT DEFAULT NULL, INDEX IDX_195DAB3C911ADE33 (idFileVersions), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_versions (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(191) NOT NULL, version INT NOT NULL, subVersion INT DEFAULT 0 NOT NULL, size INT NOT NULL, downloadCounter INT DEFAULT 0 NOT NULL, storageOptions LONGTEXT DEFAULT NULL, mimeType VARCHAR(191) DEFAULT NULL, properties VARCHAR(1000) DEFAULT NULL, focusPointX INT DEFAULT NULL, focusPointY INT DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idFileVersionsMetaDefault INT DEFAULT NULL, idFiles INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_7B6E89456B801096 (idFileVersionsMetaDefault), INDEX IDX_7B6E894511F10344 (idFiles), INDEX IDX_7B6E8945DBF11E1D (idUsersCreator), INDEX IDX_7B6E894530D07CD5 (idUsersChanger), INDEX IDX_7B6E8945D8F2A087 (mimeType), INDEX IDX_7B6E8945F7C0246A (size), INDEX IDX_7B6E8945BF1CD3C3 (version), INDEX IDX_7B6E89455E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_version_tags (idFileVersions INT NOT NULL, idTags INT NOT NULL, INDEX IDX_150A30BE911ADE33 (idFileVersions), INDEX IDX_150A30BE1C41CAB8 (idTags), PRIMARY KEY(idFileVersions, idTags)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_version_categories (idFileVersions INT NOT NULL, idCategories INT NOT NULL, INDEX IDX_2F1E17D0911ADE33 (idFileVersions), INDEX IDX_2F1E17D0B8075882 (idCategories), PRIMARY KEY(idFileVersions, idCategories)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_file_version_target_groups (idFileVersions INT NOT NULL, idTargetGroups INT NOT NULL, INDEX IDX_4F3183AD911ADE33 (idFileVersions), INDEX IDX_4F3183AD9FCCEF27 (idTargetGroups), PRIMARY KEY(idFileVersions, idTargetGroups)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_files (id INT AUTO_INCREMENT NOT NULL, version INT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idMedia INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_CA8D04277DE8E211 (idMedia), INDEX IDX_CA8D0427DBF11E1D (idUsersCreator), INDEX IDX_CA8D042730D07CD5 (idUsersChanger), INDEX IDX_CA8D0427BF1CD3C3 (version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_format_options (format_key VARCHAR(191) NOT NULL, crop_x INT NOT NULL, crop_y INT NOT NULL, crop_width INT NOT NULL, crop_height INT NOT NULL, fileVersion INT NOT NULL, INDEX IDX_6D25443B31852B63 (fileVersion), PRIMARY KEY(format_key, fileVersion)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_media (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idMediaTypes INT NOT NULL, idPreviewImage INT DEFAULT NULL, idCollections INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_A694E57284671716 (idMediaTypes), UNIQUE INDEX UNIQ_A694E572D1EB44DE (idPreviewImage), INDEX IDX_A694E57293782C96 (idCollections), INDEX IDX_A694E572DBF11E1D (idUsersCreator), INDEX IDX_A694E57230D07CD5 (idUsersChanger), INDEX IDX_A694E572A3F33DFA (changed), INDEX IDX_A694E572B23DB7B8 (created), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE me_media_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(191) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_9A01D6E85E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pr_preview_links (id INT AUTO_INCREMENT NOT NULL, token VARCHAR(12) NOT NULL, resourceKey VARCHAR(255) NOT NULL, resourceId VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, options LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', visitCount INT NOT NULL, lastVisit DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_EFB5DBF25F37A13B (token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ro_routes (id INT AUTO_INCREMENT NOT NULL, target_id INT DEFAULT NULL, path VARCHAR(191) NOT NULL, locale VARCHAR(8) NOT NULL, entity_class VARCHAR(191) NOT NULL, entity_id VARCHAR(191) NOT NULL, history TINYINT(1) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_671DB7A4158E0B66 (target_id), INDEX IDX_671DB7A4DBF11E1D (idUsersCreator), INDEX IDX_671DB7A430D07CD5 (idUsersChanger), INDEX IDX_671DB7A4B548B0F (path), INDEX IDX_671DB7A44180C698 (locale), INDEX idx_resource (entity_id, entity_class), INDEX idx_history (history), UNIQUE INDEX UNIQ_671DB7A4B548B0F4180C698 (path, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_access_controls (id INT AUTO_INCREMENT NOT NULL, permissions SMALLINT NOT NULL, entityId VARCHAR(36) NOT NULL, entityClass VARCHAR(191) NOT NULL, entityIdInteger INT DEFAULT NULL, idRoles INT NOT NULL, INDEX IDX_C526DC52A1FA6DDA (idRoles), INDEX IDX_C526DC52F62829FC (entityId), INDEX IDX_C526DC523963FFAB (entityClass), INDEX IDX_C526DC524473BB7A (entityIdInteger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_groups (id INT AUTO_INCREMENT NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, name VARCHAR(60) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idGroupsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, INDEX IDX_231E44ECBF274AB0 (idGroupsParent), INDEX IDX_231E44ECDBF11E1D (idUsersCreator), INDEX IDX_231E44EC30D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_group_roles (idGroups INT NOT NULL, idRoles INT NOT NULL, INDEX IDX_9713F725937C91EA (idGroups), INDEX IDX_9713F725A1FA6DDA (idRoles), PRIMARY KEY(idGroups, idRoles)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_permissions (id INT AUTO_INCREMENT NOT NULL, context VARCHAR(191) NOT NULL, module VARCHAR(60) DEFAULT NULL, permissions SMALLINT NOT NULL, idRoles INT DEFAULT NULL, INDEX IDX_5CEC3EEAA1FA6DDA (idRoles), UNIQUE INDEX UNIQ_5CEC3EEAE25D857EC242628A1FA6DDA (context, module, idRoles), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_role_settings (id INT AUTO_INCREMENT NOT NULL, settingKey VARCHAR(191) NOT NULL, value LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', roleId INT DEFAULT NULL, INDEX IDX_DAD1C8CBB8C2FD88 (roleId), INDEX IDX_DAD1C8CB3AA9950B (settingKey), UNIQUE INDEX UNIQ_DAD1C8CB3AA9950BB8C2FD88 (settingKey, roleId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_roles (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, role_key VARCHAR(60) DEFAULT NULL, securitySystem VARCHAR(60) NOT NULL, anonymous TINYINT(1) DEFAULT 0 NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idSecurityTypes INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_13B749A05E237E06 (name), UNIQUE INDEX UNIQ_13B749A03EF22FDB (role_key), INDEX IDX_13B749A0D02106C0 (idSecurityTypes), INDEX IDX_13B749A0DBF11E1D (idUsersCreator), INDEX IDX_13B749A030D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_security_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_user_groups (id INT AUTO_INCREMENT NOT NULL, locale LONGTEXT NOT NULL, idGroups INT DEFAULT NULL, idUsers INT DEFAULT NULL, INDEX IDX_E43ED0C8937C91EA (idGroups), INDEX IDX_E43ED0C8347E6F4 (idUsers), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_user_roles (id INT AUTO_INCREMENT NOT NULL, locale LONGTEXT NOT NULL, idUsers INT DEFAULT NULL, idRoles INT DEFAULT NULL, INDEX IDX_E48BD9DB347E6F4 (idUsers), INDEX IDX_E48BD9DBA1FA6DDA (idRoles), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_user_settings (settingsValue LONGTEXT NOT NULL, settingsKey VARCHAR(150) NOT NULL, idUsers INT NOT NULL, INDEX IDX_108FCAFA347E6F4 (idUsers), PRIMARY KEY(settingsKey, idUsers)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE se_users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(60) NOT NULL, password VARCHAR(128) NOT NULL, locale VARCHAR(60) NOT NULL, salt VARCHAR(60) NOT NULL, locked TINYINT(1) DEFAULT 0 NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, lastLogin DATETIME DEFAULT NULL, confirmationKey VARCHAR(128) DEFAULT NULL, passwordResetToken VARCHAR(80) DEFAULT NULL, passwordResetTokenExpiresAt DATETIME DEFAULT NULL, passwordResetTokenEmailsSent INT DEFAULT 0, privateKey VARCHAR(2000) DEFAULT NULL, apiKey CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', email VARCHAR(191) DEFAULT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idContacts INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_B10AC28EF85E0677 (username), UNIQUE INDEX UNIQ_B10AC28EADC1CD13 (passwordResetToken), UNIQUE INDEX UNIQ_B10AC28EE7927C74 (email), UNIQUE INDEX UNIQ_B10AC28E60E33F28 (idContacts), INDEX IDX_B10AC28EDBF11E1D (idUsersCreator), INDEX IDX_B10AC28E30D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ta_tags (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(191) NOT NULL, created DATETIME NOT NULL, changed DATETIME NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, UNIQUE INDEX UNIQ_B258E4995E237E06 (name), INDEX IDX_B258E499DBF11E1D (idUsersCreator), INDEX IDX_B258E49930D07CD5 (idUsersChanger), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tr_trash_item_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(191) DEFAULT NULL, title VARCHAR(191) NOT NULL, trashItemId INT NOT NULL, INDEX IDX_8264DAF45C8D7CA (trashItemId), UNIQUE INDEX UNIQ_8264DAF45C8D7CA4180C698 (trashItemId, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tr_trash_items (id INT AUTO_INCREMENT NOT NULL, resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, restoreData LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', restoreType VARCHAR(191) DEFAULT NULL, restoreOptions LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', resourceSecurityContext VARCHAR(191) DEFAULT NULL, resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, storeTimestamp DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', defaultLocale VARCHAR(191) DEFAULT NULL, userId INT DEFAULT NULL, INDEX IDX_102989B64B64DCC (userId), INDEX IDX_102989B5DAEB55C8CF57CB1 (resourceKey, resourceId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE we_analytics (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, webspace_key VARCHAR(191) NOT NULL, all_domains TINYINT(1) NOT NULL, content LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', type VARCHAR(60) NOT NULL, INDEX IDX_4E50BB8D1640EFD3 (all_domains), INDEX IDX_4E50BB8DAE248174 (webspace_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE we_analytics_domains (analytics INT NOT NULL, domain INT NOT NULL, INDEX IDX_F9323B6EEAC2E688 (analytics), INDEX IDX_F9323B6EA7A91E0B (domain), PRIMARY KEY(analytics, domain)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE we_domains (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(191) NOT NULL, environment VARCHAR(10) NOT NULL, INDEX IDX_7CFAB3F5F47645AE (url), INDEX IDX_7CFAB3F54626DE22 (environment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_namespaces (prefix VARCHAR(191) NOT NULL, uri VARCHAR(255) NOT NULL, PRIMARY KEY(prefix)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_workspaces (name VARCHAR(191) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_nodes (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(191) NOT NULL, parent VARCHAR(191) NOT NULL, local_name VARCHAR(191) NOT NULL, namespace VARCHAR(191) NOT NULL, workspace_name VARCHAR(191) NOT NULL, identifier VARCHAR(191) NOT NULL, type VARCHAR(191) NOT NULL, props LONGTEXT NOT NULL, numerical_props LONGTEXT DEFAULT NULL, depth INT NOT NULL, sort_order INT DEFAULT NULL, UNIQUE INDEX UNIQ_A4624AD7B548B0F1AC10DC4 (path, workspace_name), UNIQUE INDEX UNIQ_A4624AD7772E836A1AC10DC4 (identifier, workspace_name), INDEX IDX_A4624AD73D8E604F (parent), INDEX IDX_A4624AD78CDE5729 (type), INDEX IDX_A4624AD7623C14D533E16B56 (local_name, namespace), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_internal_index_types (type VARCHAR(191) NOT NULL, node_id INT NOT NULL, PRIMARY KEY(type, node_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_binarydata (id INT AUTO_INCREMENT NOT NULL, node_id INT NOT NULL, property_name VARCHAR(191) NOT NULL, workspace_name VARCHAR(191) NOT NULL, idx INT DEFAULT 0 NOT NULL, data LONGBLOB NOT NULL, UNIQUE INDEX UNIQ_37E65615460D9FD7413BC13C1AC10DC4E7087E10 (node_id, property_name, workspace_name, idx), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_nodes_references (source_id INT NOT NULL, source_property_name VARCHAR(191) NOT NULL, target_id INT NOT NULL, INDEX IDX_F3BF7E1158E0B66 (target_id), PRIMARY KEY(source_id, source_property_name, target_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_nodes_weakreferences (source_id INT NOT NULL, source_property_name VARCHAR(191) NOT NULL, target_id INT NOT NULL, INDEX IDX_F0E4F6FA158E0B66 (target_id), PRIMARY KEY(source_id, source_property_name, target_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_type_nodes (node_type_id INT AUTO_INCREMENT NOT NULL, name VARCHAR(191) NOT NULL, supertypes VARCHAR(255) NOT NULL, is_abstract TINYINT(1) NOT NULL, is_mixin TINYINT(1) NOT NULL, queryable TINYINT(1) NOT NULL, orderable_child_nodes TINYINT(1) NOT NULL, primary_item VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_34B0A8095E237E06 (name), PRIMARY KEY(node_type_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_type_props (node_type_id INT NOT NULL, name VARCHAR(191) NOT NULL, protected TINYINT(1) NOT NULL, auto_created TINYINT(1) NOT NULL, mandatory TINYINT(1) NOT NULL, on_parent_version INT NOT NULL, multiple TINYINT(1) NOT NULL, fulltext_searchable TINYINT(1) NOT NULL, query_orderable TINYINT(1) NOT NULL, required_type INT NOT NULL, query_operators INT NOT NULL, default_value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(node_type_id, name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_type_childs (id INT AUTO_INCREMENT NOT NULL, node_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, protected TINYINT(1) NOT NULL, auto_created TINYINT(1) NOT NULL, mandatory TINYINT(1) NOT NULL, on_parent_version INT NOT NULL, primary_types VARCHAR(255) NOT NULL, default_type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE ac_activities ADD CONSTRAINT FK_3EE015D064B64DCC FOREIGN KEY (userId) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE at_target_group_conditions ADD CONSTRAINT FK_94078B9989EB12AB FOREIGN KEY (idTargetGroupRules) REFERENCES at_target_group_rules (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE at_target_group_rules ADD CONSTRAINT FK_189AEDAD9FCCEF27 FOREIGN KEY (idTargetGroups) REFERENCES at_target_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE at_target_group_webspaces ADD CONSTRAINT FK_4B0C69E59FCCEF27 FOREIGN KEY (idTargetGroups) REFERENCES at_target_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D78937A3C3B1 FOREIGN KEY (idCategoriesParent) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D789DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D78930D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_category_meta ADD CONSTRAINT FK_2575BBB0B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translation_medias ADD CONSTRAINT FK_39FC41BA17CA14DA FOREIGN KEY (idCategoryTranslations) REFERENCES ca_category_translations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translation_medias ADD CONSTRAINT FK_39FC41BA7DE8E211 FOREIGN KEY (idMedia) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E3B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E3DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E330D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_keywords ADD CONSTRAINT FK_FE02CA0BDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_keywords ADD CONSTRAINT FK_FE02CA0B30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ca_category_translation_keywords ADD CONSTRAINT FK_D15FBE37F9FC9F05 FOREIGN KEY (idKeywords) REFERENCES ca_keywords (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ca_category_translation_keywords ADD CONSTRAINT FK_D15FBE3717CA14DA FOREIGN KEY (idCategoryTranslations) REFERENCES ca_category_translations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_addresses ADD CONSTRAINT FK_4165FE4893205E40 FOREIGN KEY (idAddresses) REFERENCES co_addresses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_addresses ADD CONSTRAINT FK_4165FE48996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E2A75CE2A FOREIGN KEY (idPositions) REFERENCES co_positions (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E60E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14A6D4A8651 FOREIGN KEY (idContactsMain) REFERENCES co_contacts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14AC9171171 FOREIGN KEY (idAccountsParent) REFERENCES co_accounts (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14AE48E9A13 FOREIGN KEY (logo) REFERENCES me_media (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14ADBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14A30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_account_urls ADD CONSTRAINT FK_ADF18382996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_urls ADD CONSTRAINT FK_ADF183825969693F FOREIGN KEY (idUrls) REFERENCES co_urls (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_phones ADD CONSTRAINT FK_918DA964996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_phones ADD CONSTRAINT FK_918DA9648039866F FOREIGN KEY (idPhones) REFERENCES co_phones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_emails ADD CONSTRAINT FK_3E246FC3996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_emails ADD CONSTRAINT FK_3E246FC32F9040C8 FOREIGN KEY (idEmails) REFERENCES co_emails (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_notes ADD CONSTRAINT FK_A3FBB24A996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_notes ADD CONSTRAINT FK_A3FBB24A16DFE591 FOREIGN KEY (idNotes) REFERENCES co_notes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_faxes ADD CONSTRAINT FK_7A4E77DC996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_faxes ADD CONSTRAINT FK_7A4E77DCCF6A2007 FOREIGN KEY (idFaxes) REFERENCES co_faxes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_social_media_profiles ADD CONSTRAINT FK_E06F75F5996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_social_media_profiles ADD CONSTRAINT FK_E06F75F5573F8344 FOREIGN KEY (idSocialMediaProfiles) REFERENCES co_social_media_profiles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_bank_accounts ADD CONSTRAINT FK_C873A532996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_bank_accounts ADD CONSTRAINT FK_C873A53237FCD1D8 FOREIGN KEY (idBankAccounts) REFERENCES co_bank_account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_categories ADD CONSTRAINT FK_B60E9510996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_categories ADD CONSTRAINT FK_B60E9510B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_medias ADD CONSTRAINT FK_60772810996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_medias ADD CONSTRAINT FK_6077281071C3071B FOREIGN KEY (idMedias) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_tags ADD CONSTRAINT FK_E8D92005996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_account_tags ADD CONSTRAINT FK_E8D920051C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_addresses ADD CONSTRAINT FK_26E9A6142A37021A FOREIGN KEY (idAdressTypes) REFERENCES co_address_types (id)');
        $this->addSql('ALTER TABLE co_contact_addresses ADD CONSTRAINT FK_DEE056893205E40 FOREIGN KEY (idAddresses) REFERENCES co_addresses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_addresses ADD CONSTRAINT FK_DEE056860E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_locales ADD CONSTRAINT FK_31E5672760E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id)');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A95A254E939 FOREIGN KEY (idTitles) REFERENCES co_contact_titles (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A951677722F FOREIGN KEY (avatar) REFERENCES me_media (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A95DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A9530D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE co_contact_urls ADD CONSTRAINT FK_99D86D760E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_urls ADD CONSTRAINT FK_99D86D75969693F FOREIGN KEY (idUrls) REFERENCES co_urls (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_notes ADD CONSTRAINT FK_B85E7B3460E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_notes ADD CONSTRAINT FK_B85E7B3416DFE591 FOREIGN KEY (idNotes) REFERENCES co_notes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_emails ADD CONSTRAINT FK_8982963160E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_emails ADD CONSTRAINT FK_898296312F9040C8 FOREIGN KEY (idEmails) REFERENCES co_emails (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_phones ADD CONSTRAINT FK_262B509660E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_phones ADD CONSTRAINT FK_262B50968039866F FOREIGN KEY (idPhones) REFERENCES co_phones (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_faxes ADD CONSTRAINT FK_61EBBEA260E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_faxes ADD CONSTRAINT FK_61EBBEA2CF6A2007 FOREIGN KEY (idFaxes) REFERENCES co_faxes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles ADD CONSTRAINT FK_74FF4CC060E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles ADD CONSTRAINT FK_74FF4CC0573F8344 FOREIGN KEY (idSocialMediaProfiles) REFERENCES co_social_media_profiles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_bank_accounts ADD CONSTRAINT FK_76CDDA0660E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_bank_accounts ADD CONSTRAINT FK_76CDDA0637FCD1D8 FOREIGN KEY (idBankAccounts) REFERENCES co_bank_account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_medias ADD CONSTRAINT FK_D7D1D1E260E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_medias ADD CONSTRAINT FK_D7D1D1E271C3071B FOREIGN KEY (idMedias) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_categories ADD CONSTRAINT FK_8D2C3E2360E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_categories ADD CONSTRAINT FK_8D2C3E23B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_tags ADD CONSTRAINT FK_4CB5255060E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_contact_tags ADD CONSTRAINT FK_4CB525501C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE co_emails ADD CONSTRAINT FK_A2F2CB77D816E840 FOREIGN KEY (idEmailTypes) REFERENCES co_email_types (id)');
        $this->addSql('ALTER TABLE co_faxes ADD CONSTRAINT FK_A5EC6A18B466C5DA FOREIGN KEY (idFaxTypes) REFERENCES co_fax_types (id)');
        $this->addSql('ALTER TABLE co_phones ADD CONSTRAINT FK_D5B0DD0A4249AD7 FOREIGN KEY (idPhoneTypes) REFERENCES co_phone_types (id)');
        $this->addSql('ALTER TABLE co_social_media_profiles ADD CONSTRAINT FK_DF585BFBB5BEA95F FOREIGN KEY (idSocialMediaTypes) REFERENCES co_social_media_profile_types (id)');
        $this->addSql('ALTER TABLE co_urls ADD CONSTRAINT FK_6F03842E882335CC FOREIGN KEY (idUrlTypes) REFERENCES co_url_types (id)');
        $this->addSql('ALTER TABLE me_collection_meta ADD CONSTRAINT FK_F8D5E71693782C96 FOREIGN KEY (idCollections) REFERENCES me_collections (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887CFA3F467 FOREIGN KEY (idCollectionsMetaDefault) REFERENCES me_collection_meta (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887E67924D6 FOREIGN KEY (idCollectionTypes) REFERENCES me_collection_types (id)');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887A4F2DCF8 FOREIGN KEY (idCollectionsParent) REFERENCES me_collections (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D488730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_version_content_languages ADD CONSTRAINT FK_F3FD652C911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_meta ADD CONSTRAINT FK_AD44B0AD911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_publish_languages ADD CONSTRAINT FK_195DAB3C911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E89456B801096 FOREIGN KEY (idFileVersionsMetaDefault) REFERENCES me_file_version_meta (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E894511F10344 FOREIGN KEY (idFiles) REFERENCES me_files (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E8945DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E894530D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_file_version_tags ADD CONSTRAINT FK_150A30BE911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_tags ADD CONSTRAINT FK_150A30BE1C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_categories ADD CONSTRAINT FK_2F1E17D0911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_categories ADD CONSTRAINT FK_2F1E17D0B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_target_groups ADD CONSTRAINT FK_4F3183AD911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_file_version_target_groups ADD CONSTRAINT FK_4F3183AD9FCCEF27 FOREIGN KEY (idTargetGroups) REFERENCES at_target_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D04277DE8E211 FOREIGN KEY (idMedia) REFERENCES me_media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D0427DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D042730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_format_options ADD CONSTRAINT FK_6D25443B31852B63 FOREIGN KEY (fileVersion) REFERENCES me_file_versions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57284671716 FOREIGN KEY (idMediaTypes) REFERENCES me_media_types (id)');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E572D1EB44DE FOREIGN KEY (idPreviewImage) REFERENCES me_media (id)');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57293782C96 FOREIGN KEY (idCollections) REFERENCES me_collections (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E572DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57230D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A4158E0B66 FOREIGN KEY (target_id) REFERENCES ro_routes (id)');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A4DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A430D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_access_controls ADD CONSTRAINT FK_C526DC52A1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_groups ADD CONSTRAINT FK_231E44ECBF274AB0 FOREIGN KEY (idGroupsParent) REFERENCES se_groups (id)');
        $this->addSql('ALTER TABLE se_groups ADD CONSTRAINT FK_231E44ECDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_groups ADD CONSTRAINT FK_231E44EC30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_group_roles ADD CONSTRAINT FK_9713F725937C91EA FOREIGN KEY (idGroups) REFERENCES se_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_group_roles ADD CONSTRAINT FK_9713F725A1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_permissions ADD CONSTRAINT FK_5CEC3EEAA1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_role_settings ADD CONSTRAINT FK_DAD1C8CBB8C2FD88 FOREIGN KEY (roleId) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A0D02106C0 FOREIGN KEY (idSecurityTypes) REFERENCES se_security_types (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A0DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A030D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_user_groups ADD CONSTRAINT FK_E43ED0C8937C91EA FOREIGN KEY (idGroups) REFERENCES se_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_groups ADD CONSTRAINT FK_E43ED0C8347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_roles ADD CONSTRAINT FK_E48BD9DB347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_roles ADD CONSTRAINT FK_E48BD9DBA1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_user_settings ADD CONSTRAINT FK_108FCAFA347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28E60E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28EDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28E30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ta_tags ADD CONSTRAINT FK_B258E499DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ta_tags ADD CONSTRAINT FK_B258E49930D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE tr_trash_item_translations ADD CONSTRAINT FK_8264DAF45C8D7CA FOREIGN KEY (trashItemId) REFERENCES tr_trash_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tr_trash_items ADD CONSTRAINT FK_102989B64B64DCC FOREIGN KEY (userId) REFERENCES se_users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE we_analytics_domains ADD CONSTRAINT FK_F9323B6EEAC2E688 FOREIGN KEY (analytics) REFERENCES we_analytics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE we_analytics_domains ADD CONSTRAINT FK_F9323B6EA7A91E0B FOREIGN KEY (domain) REFERENCES we_domains (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->skipIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\MariaDb1027Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\MariaDb1027Platform'."
        );

        $this->addSql('ALTER TABLE ac_activities DROP FOREIGN KEY FK_3EE015D064B64DCC');
        $this->addSql('ALTER TABLE at_target_group_conditions DROP FOREIGN KEY FK_94078B9989EB12AB');
        $this->addSql('ALTER TABLE at_target_group_rules DROP FOREIGN KEY FK_189AEDAD9FCCEF27');
        $this->addSql('ALTER TABLE at_target_group_webspaces DROP FOREIGN KEY FK_4B0C69E59FCCEF27');
        $this->addSql('ALTER TABLE ca_categories DROP FOREIGN KEY FK_3D85D78937A3C3B1');
        $this->addSql('ALTER TABLE ca_categories DROP FOREIGN KEY FK_3D85D789DBF11E1D');
        $this->addSql('ALTER TABLE ca_categories DROP FOREIGN KEY FK_3D85D78930D07CD5');
        $this->addSql('ALTER TABLE ca_category_meta DROP FOREIGN KEY FK_2575BBB0B8075882');
        $this->addSql('ALTER TABLE ca_category_translation_medias DROP FOREIGN KEY FK_39FC41BA17CA14DA');
        $this->addSql('ALTER TABLE ca_category_translation_medias DROP FOREIGN KEY FK_39FC41BA7DE8E211');
        $this->addSql('ALTER TABLE ca_category_translations DROP FOREIGN KEY FK_5DCED5E3B8075882');
        $this->addSql('ALTER TABLE ca_category_translations DROP FOREIGN KEY FK_5DCED5E3DBF11E1D');
        $this->addSql('ALTER TABLE ca_category_translations DROP FOREIGN KEY FK_5DCED5E330D07CD5');
        $this->addSql('ALTER TABLE ca_keywords DROP FOREIGN KEY FK_FE02CA0BDBF11E1D');
        $this->addSql('ALTER TABLE ca_keywords DROP FOREIGN KEY FK_FE02CA0B30D07CD5');
        $this->addSql('ALTER TABLE ca_category_translation_keywords DROP FOREIGN KEY FK_D15FBE37F9FC9F05');
        $this->addSql('ALTER TABLE ca_category_translation_keywords DROP FOREIGN KEY FK_D15FBE3717CA14DA');
        $this->addSql('ALTER TABLE co_account_addresses DROP FOREIGN KEY FK_4165FE4893205E40');
        $this->addSql('ALTER TABLE co_account_addresses DROP FOREIGN KEY FK_4165FE48996BB4F7');
        $this->addSql('ALTER TABLE co_account_contacts DROP FOREIGN KEY FK_28C6CA0E2A75CE2A');
        $this->addSql('ALTER TABLE co_account_contacts DROP FOREIGN KEY FK_28C6CA0E60E33F28');
        $this->addSql('ALTER TABLE co_account_contacts DROP FOREIGN KEY FK_28C6CA0E996BB4F7');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14A6D4A8651');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14AC9171171');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14AE48E9A13');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14ADBF11E1D');
        $this->addSql('ALTER TABLE co_accounts DROP FOREIGN KEY FK_805CD14A30D07CD5');
        $this->addSql('ALTER TABLE co_account_urls DROP FOREIGN KEY FK_ADF18382996BB4F7');
        $this->addSql('ALTER TABLE co_account_urls DROP FOREIGN KEY FK_ADF183825969693F');
        $this->addSql('ALTER TABLE co_account_phones DROP FOREIGN KEY FK_918DA964996BB4F7');
        $this->addSql('ALTER TABLE co_account_phones DROP FOREIGN KEY FK_918DA9648039866F');
        $this->addSql('ALTER TABLE co_account_emails DROP FOREIGN KEY FK_3E246FC3996BB4F7');
        $this->addSql('ALTER TABLE co_account_emails DROP FOREIGN KEY FK_3E246FC32F9040C8');
        $this->addSql('ALTER TABLE co_account_notes DROP FOREIGN KEY FK_A3FBB24A996BB4F7');
        $this->addSql('ALTER TABLE co_account_notes DROP FOREIGN KEY FK_A3FBB24A16DFE591');
        $this->addSql('ALTER TABLE co_account_faxes DROP FOREIGN KEY FK_7A4E77DC996BB4F7');
        $this->addSql('ALTER TABLE co_account_faxes DROP FOREIGN KEY FK_7A4E77DCCF6A2007');
        $this->addSql('ALTER TABLE co_account_social_media_profiles DROP FOREIGN KEY FK_E06F75F5996BB4F7');
        $this->addSql('ALTER TABLE co_account_social_media_profiles DROP FOREIGN KEY FK_E06F75F5573F8344');
        $this->addSql('ALTER TABLE co_account_bank_accounts DROP FOREIGN KEY FK_C873A532996BB4F7');
        $this->addSql('ALTER TABLE co_account_bank_accounts DROP FOREIGN KEY FK_C873A53237FCD1D8');
        $this->addSql('ALTER TABLE co_account_categories DROP FOREIGN KEY FK_B60E9510996BB4F7');
        $this->addSql('ALTER TABLE co_account_categories DROP FOREIGN KEY FK_B60E9510B8075882');
        $this->addSql('ALTER TABLE co_account_medias DROP FOREIGN KEY FK_60772810996BB4F7');
        $this->addSql('ALTER TABLE co_account_medias DROP FOREIGN KEY FK_6077281071C3071B');
        $this->addSql('ALTER TABLE co_account_tags DROP FOREIGN KEY FK_E8D92005996BB4F7');
        $this->addSql('ALTER TABLE co_account_tags DROP FOREIGN KEY FK_E8D920051C41CAB8');
        $this->addSql('ALTER TABLE co_addresses DROP FOREIGN KEY FK_26E9A6142A37021A');
        $this->addSql('ALTER TABLE co_contact_addresses DROP FOREIGN KEY FK_DEE056893205E40');
        $this->addSql('ALTER TABLE co_contact_addresses DROP FOREIGN KEY FK_DEE056860E33F28');
        $this->addSql('ALTER TABLE co_contact_locales DROP FOREIGN KEY FK_31E5672760E33F28');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A95A254E939');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A951677722F');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A95DBF11E1D');
        $this->addSql('ALTER TABLE co_contacts DROP FOREIGN KEY FK_79D45A9530D07CD5');
        $this->addSql('ALTER TABLE co_contact_urls DROP FOREIGN KEY FK_99D86D760E33F28');
        $this->addSql('ALTER TABLE co_contact_urls DROP FOREIGN KEY FK_99D86D75969693F');
        $this->addSql('ALTER TABLE co_contact_notes DROP FOREIGN KEY FK_B85E7B3460E33F28');
        $this->addSql('ALTER TABLE co_contact_notes DROP FOREIGN KEY FK_B85E7B3416DFE591');
        $this->addSql('ALTER TABLE co_contact_emails DROP FOREIGN KEY FK_8982963160E33F28');
        $this->addSql('ALTER TABLE co_contact_emails DROP FOREIGN KEY FK_898296312F9040C8');
        $this->addSql('ALTER TABLE co_contact_phones DROP FOREIGN KEY FK_262B509660E33F28');
        $this->addSql('ALTER TABLE co_contact_phones DROP FOREIGN KEY FK_262B50968039866F');
        $this->addSql('ALTER TABLE co_contact_faxes DROP FOREIGN KEY FK_61EBBEA260E33F28');
        $this->addSql('ALTER TABLE co_contact_faxes DROP FOREIGN KEY FK_61EBBEA2CF6A2007');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles DROP FOREIGN KEY FK_74FF4CC060E33F28');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles DROP FOREIGN KEY FK_74FF4CC0573F8344');
        $this->addSql('ALTER TABLE co_contact_bank_accounts DROP FOREIGN KEY FK_76CDDA0660E33F28');
        $this->addSql('ALTER TABLE co_contact_bank_accounts DROP FOREIGN KEY FK_76CDDA0637FCD1D8');
        $this->addSql('ALTER TABLE co_contact_medias DROP FOREIGN KEY FK_D7D1D1E260E33F28');
        $this->addSql('ALTER TABLE co_contact_medias DROP FOREIGN KEY FK_D7D1D1E271C3071B');
        $this->addSql('ALTER TABLE co_contact_categories DROP FOREIGN KEY FK_8D2C3E2360E33F28');
        $this->addSql('ALTER TABLE co_contact_categories DROP FOREIGN KEY FK_8D2C3E23B8075882');
        $this->addSql('ALTER TABLE co_contact_tags DROP FOREIGN KEY FK_4CB5255060E33F28');
        $this->addSql('ALTER TABLE co_contact_tags DROP FOREIGN KEY FK_4CB525501C41CAB8');
        $this->addSql('ALTER TABLE co_emails DROP FOREIGN KEY FK_A2F2CB77D816E840');
        $this->addSql('ALTER TABLE co_faxes DROP FOREIGN KEY FK_A5EC6A18B466C5DA');
        $this->addSql('ALTER TABLE co_phones DROP FOREIGN KEY FK_D5B0DD0A4249AD7');
        $this->addSql('ALTER TABLE co_social_media_profiles DROP FOREIGN KEY FK_DF585BFBB5BEA95F');
        $this->addSql('ALTER TABLE co_urls DROP FOREIGN KEY FK_6F03842E882335CC');
        $this->addSql('ALTER TABLE me_collection_meta DROP FOREIGN KEY FK_F8D5E71693782C96');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887CFA3F467');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887E67924D6');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887A4F2DCF8');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D4887DBF11E1D');
        $this->addSql('ALTER TABLE me_collections DROP FOREIGN KEY FK_F0D488730D07CD5');
        $this->addSql('ALTER TABLE me_file_version_content_languages DROP FOREIGN KEY FK_F3FD652C911ADE33');
        $this->addSql('ALTER TABLE me_file_version_meta DROP FOREIGN KEY FK_AD44B0AD911ADE33');
        $this->addSql('ALTER TABLE me_file_version_publish_languages DROP FOREIGN KEY FK_195DAB3C911ADE33');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E89456B801096');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E894511F10344');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E8945DBF11E1D');
        $this->addSql('ALTER TABLE me_file_versions DROP FOREIGN KEY FK_7B6E894530D07CD5');
        $this->addSql('ALTER TABLE me_file_version_tags DROP FOREIGN KEY FK_150A30BE911ADE33');
        $this->addSql('ALTER TABLE me_file_version_tags DROP FOREIGN KEY FK_150A30BE1C41CAB8');
        $this->addSql('ALTER TABLE me_file_version_categories DROP FOREIGN KEY FK_2F1E17D0911ADE33');
        $this->addSql('ALTER TABLE me_file_version_categories DROP FOREIGN KEY FK_2F1E17D0B8075882');
        $this->addSql('ALTER TABLE me_file_version_target_groups DROP FOREIGN KEY FK_4F3183AD911ADE33');
        $this->addSql('ALTER TABLE me_file_version_target_groups DROP FOREIGN KEY FK_4F3183AD9FCCEF27');
        $this->addSql('ALTER TABLE me_files DROP FOREIGN KEY FK_CA8D04277DE8E211');
        $this->addSql('ALTER TABLE me_files DROP FOREIGN KEY FK_CA8D0427DBF11E1D');
        $this->addSql('ALTER TABLE me_files DROP FOREIGN KEY FK_CA8D042730D07CD5');
        $this->addSql('ALTER TABLE me_format_options DROP FOREIGN KEY FK_6D25443B31852B63');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E57284671716');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E572D1EB44DE');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E57293782C96');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E572DBF11E1D');
        $this->addSql('ALTER TABLE me_media DROP FOREIGN KEY FK_A694E57230D07CD5');
        $this->addSql('ALTER TABLE ro_routes DROP FOREIGN KEY FK_671DB7A4158E0B66');
        $this->addSql('ALTER TABLE ro_routes DROP FOREIGN KEY FK_671DB7A4DBF11E1D');
        $this->addSql('ALTER TABLE ro_routes DROP FOREIGN KEY FK_671DB7A430D07CD5');
        $this->addSql('ALTER TABLE se_access_controls DROP FOREIGN KEY FK_C526DC52A1FA6DDA');
        $this->addSql('ALTER TABLE se_groups DROP FOREIGN KEY FK_231E44ECBF274AB0');
        $this->addSql('ALTER TABLE se_groups DROP FOREIGN KEY FK_231E44ECDBF11E1D');
        $this->addSql('ALTER TABLE se_groups DROP FOREIGN KEY FK_231E44EC30D07CD5');
        $this->addSql('ALTER TABLE se_group_roles DROP FOREIGN KEY FK_9713F725937C91EA');
        $this->addSql('ALTER TABLE se_group_roles DROP FOREIGN KEY FK_9713F725A1FA6DDA');
        $this->addSql('ALTER TABLE se_permissions DROP FOREIGN KEY FK_5CEC3EEAA1FA6DDA');
        $this->addSql('ALTER TABLE se_role_settings DROP FOREIGN KEY FK_DAD1C8CBB8C2FD88');
        $this->addSql('ALTER TABLE se_roles DROP FOREIGN KEY FK_13B749A0D02106C0');
        $this->addSql('ALTER TABLE se_roles DROP FOREIGN KEY FK_13B749A0DBF11E1D');
        $this->addSql('ALTER TABLE se_roles DROP FOREIGN KEY FK_13B749A030D07CD5');
        $this->addSql('ALTER TABLE se_user_groups DROP FOREIGN KEY FK_E43ED0C8937C91EA');
        $this->addSql('ALTER TABLE se_user_groups DROP FOREIGN KEY FK_E43ED0C8347E6F4');
        $this->addSql('ALTER TABLE se_user_roles DROP FOREIGN KEY FK_E48BD9DB347E6F4');
        $this->addSql('ALTER TABLE se_user_roles DROP FOREIGN KEY FK_E48BD9DBA1FA6DDA');
        $this->addSql('ALTER TABLE se_user_settings DROP FOREIGN KEY FK_108FCAFA347E6F4');
        $this->addSql('ALTER TABLE se_users DROP FOREIGN KEY FK_B10AC28E60E33F28');
        $this->addSql('ALTER TABLE se_users DROP FOREIGN KEY FK_B10AC28EDBF11E1D');
        $this->addSql('ALTER TABLE se_users DROP FOREIGN KEY FK_B10AC28E30D07CD5');
        $this->addSql('ALTER TABLE ta_tags DROP FOREIGN KEY FK_B258E499DBF11E1D');
        $this->addSql('ALTER TABLE ta_tags DROP FOREIGN KEY FK_B258E49930D07CD5');
        $this->addSql('ALTER TABLE tr_trash_item_translations DROP FOREIGN KEY FK_8264DAF45C8D7CA');
        $this->addSql('ALTER TABLE tr_trash_items DROP FOREIGN KEY FK_102989B64B64DCC');
        $this->addSql('ALTER TABLE we_analytics_domains DROP FOREIGN KEY FK_F9323B6EEAC2E688');
        $this->addSql('ALTER TABLE we_analytics_domains DROP FOREIGN KEY FK_F9323B6EA7A91E0B');
        $this->addSql('DROP TABLE ac_activities');
        $this->addSql('DROP TABLE at_target_group_conditions');
        $this->addSql('DROP TABLE at_target_group_rules');
        $this->addSql('DROP TABLE at_target_group_webspaces');
        $this->addSql('DROP TABLE at_target_groups');
        $this->addSql('DROP TABLE ca_categories');
        $this->addSql('DROP TABLE ca_category_meta');
        $this->addSql('DROP TABLE ca_category_translation_medias');
        $this->addSql('DROP TABLE ca_category_translations');
        $this->addSql('DROP TABLE ca_keywords');
        $this->addSql('DROP TABLE ca_category_translation_keywords');
        $this->addSql('DROP TABLE co_account_addresses');
        $this->addSql('DROP TABLE co_account_contacts');
        $this->addSql('DROP TABLE co_accounts');
        $this->addSql('DROP TABLE co_account_urls');
        $this->addSql('DROP TABLE co_account_phones');
        $this->addSql('DROP TABLE co_account_emails');
        $this->addSql('DROP TABLE co_account_notes');
        $this->addSql('DROP TABLE co_account_faxes');
        $this->addSql('DROP TABLE co_account_social_media_profiles');
        $this->addSql('DROP TABLE co_account_bank_accounts');
        $this->addSql('DROP TABLE co_account_categories');
        $this->addSql('DROP TABLE co_account_medias');
        $this->addSql('DROP TABLE co_account_tags');
        $this->addSql('DROP TABLE co_address_types');
        $this->addSql('DROP TABLE co_addresses');
        $this->addSql('DROP TABLE co_bank_account');
        $this->addSql('DROP TABLE co_contact_addresses');
        $this->addSql('DROP TABLE co_contact_locales');
        $this->addSql('DROP TABLE co_contact_titles');
        $this->addSql('DROP TABLE co_contacts');
        $this->addSql('DROP TABLE co_contact_urls');
        $this->addSql('DROP TABLE co_contact_notes');
        $this->addSql('DROP TABLE co_contact_emails');
        $this->addSql('DROP TABLE co_contact_phones');
        $this->addSql('DROP TABLE co_contact_faxes');
        $this->addSql('DROP TABLE co_contact_social_media_profiles');
        $this->addSql('DROP TABLE co_contact_bank_accounts');
        $this->addSql('DROP TABLE co_contact_medias');
        $this->addSql('DROP TABLE co_contact_categories');
        $this->addSql('DROP TABLE co_contact_tags');
        $this->addSql('DROP TABLE co_email_types');
        $this->addSql('DROP TABLE co_emails');
        $this->addSql('DROP TABLE co_fax_types');
        $this->addSql('DROP TABLE co_faxes');
        $this->addSql('DROP TABLE co_notes');
        $this->addSql('DROP TABLE co_phone_types');
        $this->addSql('DROP TABLE co_phones');
        $this->addSql('DROP TABLE co_positions');
        $this->addSql('DROP TABLE co_social_media_profile_types');
        $this->addSql('DROP TABLE co_social_media_profiles');
        $this->addSql('DROP TABLE co_url_types');
        $this->addSql('DROP TABLE co_urls');
        $this->addSql('DROP TABLE me_collection_meta');
        $this->addSql('DROP TABLE me_collection_types');
        $this->addSql('DROP TABLE me_collections');
        $this->addSql('DROP TABLE me_file_version_content_languages');
        $this->addSql('DROP TABLE me_file_version_meta');
        $this->addSql('DROP TABLE me_file_version_publish_languages');
        $this->addSql('DROP TABLE me_file_versions');
        $this->addSql('DROP TABLE me_file_version_tags');
        $this->addSql('DROP TABLE me_file_version_categories');
        $this->addSql('DROP TABLE me_file_version_target_groups');
        $this->addSql('DROP TABLE me_files');
        $this->addSql('DROP TABLE me_format_options');
        $this->addSql('DROP TABLE me_media');
        $this->addSql('DROP TABLE me_media_types');
        $this->addSql('DROP TABLE pr_preview_links');
        $this->addSql('DROP TABLE ro_routes');
        $this->addSql('DROP TABLE se_access_controls');
        $this->addSql('DROP TABLE se_groups');
        $this->addSql('DROP TABLE se_group_roles');
        $this->addSql('DROP TABLE se_permissions');
        $this->addSql('DROP TABLE se_role_settings');
        $this->addSql('DROP TABLE se_roles');
        $this->addSql('DROP TABLE se_security_types');
        $this->addSql('DROP TABLE se_user_groups');
        $this->addSql('DROP TABLE se_user_roles');
        $this->addSql('DROP TABLE se_user_settings');
        $this->addSql('DROP TABLE se_users');
        $this->addSql('DROP TABLE ta_tags');
        $this->addSql('DROP TABLE tr_trash_item_translations');
        $this->addSql('DROP TABLE tr_trash_items');
        $this->addSql('DROP TABLE we_analytics');
        $this->addSql('DROP TABLE we_analytics_domains');
        $this->addSql('DROP TABLE we_domains');
        $this->addSql('DROP TABLE phpcr_namespaces');
        $this->addSql('DROP TABLE phpcr_workspaces');
        $this->addSql('DROP TABLE phpcr_nodes');
        $this->addSql('DROP TABLE phpcr_internal_index_types');
        $this->addSql('DROP TABLE phpcr_binarydata');
        $this->addSql('DROP TABLE phpcr_nodes_references');
        $this->addSql('DROP TABLE phpcr_nodes_weakreferences');
        $this->addSql('DROP TABLE phpcr_type_nodes');
        $this->addSql('DROP TABLE phpcr_type_props');
        $this->addSql('DROP TABLE phpcr_type_childs');
    }
}
