<?php

declare(strict_types=1);

namespace Sulu\Bundle\MigrationBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221122205424 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->skipIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL100Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL100Platform'."
        );

        $this->addSql('CREATE SEQUENCE ac_activities_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE at_target_group_conditions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE at_target_group_rules_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE at_target_group_webspaces_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE at_target_groups_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ca_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ca_category_meta_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ca_category_translation_medias_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ca_category_translations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ca_keywords_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_account_addresses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_account_contacts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_accounts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_address_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_addresses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_bank_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_contact_addresses_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_contact_locales_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_contact_titles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_contacts_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_email_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_emails_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_fax_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_faxes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_notes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_phone_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_phones_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_positions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_social_media_profile_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_social_media_profiles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_url_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE co_urls_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_collection_meta_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_collection_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_collections_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_file_version_content_languages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_file_version_meta_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_file_version_publish_languages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_file_versions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_files_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_media_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE me_media_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pr_preview_links_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ro_routes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_access_controls_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_groups_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_permissions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_role_settings_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_roles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_security_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_user_groups_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_user_roles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE se_users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ta_tags_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tr_trash_item_translations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tr_trash_items_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE we_analytics_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE we_domains_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE ac_activities (id INT NOT NULL, type VARCHAR(191) NOT NULL, context JSON NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, batch VARCHAR(191) DEFAULT NULL, payload JSON DEFAULT NULL, resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, resourceLocale VARCHAR(191) DEFAULT NULL, resourceWebspaceKey VARCHAR(191) DEFAULT NULL, resourceTitle VARCHAR(191) DEFAULT NULL, resourceTitleLocale VARCHAR(191) DEFAULT NULL, resourceSecurityContext VARCHAR(191) DEFAULT NULL, resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, userId INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3EE015D064B64DCC ON ac_activities (userId)');
        $this->addSql('CREATE INDEX timestamp_idx ON ac_activities (timestamp)');
        $this->addSql('CREATE INDEX resourceKey_idx ON ac_activities (resourceKey)');
        $this->addSql('CREATE INDEX resourceId_idx ON ac_activities (resourceId)');
        $this->addSql('CREATE INDEX resourceSecurityContext_idx ON ac_activities (resourceSecurityContext)');
        $this->addSql('CREATE INDEX resourceSecurityObjectType_idx ON ac_activities (resourceSecurityObjectType)');
        $this->addSql('CREATE INDEX resourceSecurityObjectId_idx ON ac_activities (resourceSecurityObjectId)');
        $this->addSql('COMMENT ON COLUMN ac_activities.timestamp IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE at_target_group_conditions (id INT NOT NULL, "type" VARCHAR(255) NOT NULL, "condition" JSON NOT NULL, idTargetGroupRules INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_94078B9989EB12AB ON at_target_group_conditions (idTargetGroupRules)');
        $this->addSql('CREATE TABLE at_target_group_rules (id INT NOT NULL, title VARCHAR(255) NOT NULL, frequency INT NOT NULL, idTargetGroups INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_189AEDAD9FCCEF27 ON at_target_group_rules (idTargetGroups)');
        $this->addSql('CREATE TABLE at_target_group_webspaces (id INT NOT NULL, webspaceKey VARCHAR(255) NOT NULL, idTargetGroups INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B0C69E59FCCEF27 ON at_target_group_webspaces (idTargetGroups)');
        $this->addSql('CREATE TABLE at_target_groups (id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, priority INT NOT NULL, allWebspaces BOOLEAN NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ca_categories (id INT NOT NULL, category_key VARCHAR(191) DEFAULT NULL, default_locale VARCHAR(5) NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idCategoriesParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D85D789AF5206F3 ON ca_categories (category_key)');
        $this->addSql('CREATE INDEX IDX_3D85D78937A3C3B1 ON ca_categories (idCategoriesParent)');
        $this->addSql('CREATE INDEX IDX_3D85D789DBF11E1D ON ca_categories (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_3D85D78930D07CD5 ON ca_categories (idUsersChanger)');
        $this->addSql('CREATE TABLE ca_category_meta (id INT NOT NULL, meta_key VARCHAR(45) NOT NULL, value VARCHAR(255) NOT NULL, locale VARCHAR(5) DEFAULT NULL, idCategories INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2575BBB0B8075882 ON ca_category_meta (idCategories)');
        $this->addSql('CREATE TABLE ca_category_translation_medias (id INT NOT NULL, position INT DEFAULT 0 NOT NULL, idCategoryTranslations INT NOT NULL, idMedia INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_39FC41BA17CA14DA ON ca_category_translation_medias (idCategoryTranslations)');
        $this->addSql('CREATE INDEX IDX_39FC41BA7DE8E211 ON ca_category_translation_medias (idMedia)');
        $this->addSql('CREATE TABLE ca_category_translations (id INT NOT NULL, translation VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, description TEXT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idCategories INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5DCED5E3B8075882 ON ca_category_translations (idCategories)');
        $this->addSql('CREATE INDEX IDX_5DCED5E3DBF11E1D ON ca_category_translations (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_5DCED5E330D07CD5 ON ca_category_translations (idUsersChanger)');
        $this->addSql('CREATE TABLE ca_keywords (id INT NOT NULL, locale VARCHAR(5) NOT NULL, keyword VARCHAR(191) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FE02CA0BDBF11E1D ON ca_keywords (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_FE02CA0B30D07CD5 ON ca_keywords (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_FE02CA0B5A93713B ON ca_keywords (keyword)');
        $this->addSql('CREATE UNIQUE INDEX unique_idx ON ca_keywords (keyword, locale)');
        $this->addSql('CREATE TABLE ca_category_translation_keywords (idKeywords INT NOT NULL, idCategoryTranslations INT NOT NULL, PRIMARY KEY(idKeywords, idCategoryTranslations))');
        $this->addSql('CREATE INDEX IDX_D15FBE37F9FC9F05 ON ca_category_translation_keywords (idKeywords)');
        $this->addSql('CREATE INDEX IDX_D15FBE3717CA14DA ON ca_category_translation_keywords (idCategoryTranslations)');
        $this->addSql('CREATE TABLE co_account_addresses (id INT NOT NULL, main BOOLEAN NOT NULL, idAddresses INT NOT NULL, idAccounts INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4165FE4893205E40 ON co_account_addresses (idAddresses)');
        $this->addSql('CREATE INDEX IDX_4165FE48996BB4F7 ON co_account_addresses (idAccounts)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4165FE4893205E40996BB4F7 ON co_account_addresses (idAddresses, idAccounts)');
        $this->addSql('CREATE TABLE co_account_contacts (id INT NOT NULL, main BOOLEAN NOT NULL, idPositions INT DEFAULT NULL, idContacts INT NOT NULL, idAccounts INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_28C6CA0E2A75CE2A ON co_account_contacts (idPositions)');
        $this->addSql('CREATE INDEX IDX_28C6CA0E60E33F28 ON co_account_contacts (idContacts)');
        $this->addSql('CREATE INDEX IDX_28C6CA0E996BB4F7 ON co_account_contacts (idAccounts)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_28C6CA0E60E33F28996BB4F7 ON co_account_contacts (idContacts, idAccounts)');
        $this->addSql('CREATE TABLE co_accounts (id INT NOT NULL, logo INT DEFAULT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, name VARCHAR(150) NOT NULL, externalId VARCHAR(255) DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, corporation VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, uid VARCHAR(50) DEFAULT NULL, registerNumber VARCHAR(255) DEFAULT NULL, placeOfJurisdiction VARCHAR(255) DEFAULT NULL, mainEmail VARCHAR(255) DEFAULT NULL, mainPhone VARCHAR(255) DEFAULT NULL, mainFax VARCHAR(255) DEFAULT NULL, mainUrl VARCHAR(255) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idContactsMain INT DEFAULT NULL, idAccountsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_805CD14A6D4A8651 ON co_accounts (idContactsMain)');
        $this->addSql('CREATE INDEX IDX_805CD14AC9171171 ON co_accounts (idAccountsParent)');
        $this->addSql('CREATE INDEX IDX_805CD14AE48E9A13 ON co_accounts (logo)');
        $this->addSql('CREATE INDEX IDX_805CD14ADBF11E1D ON co_accounts (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_805CD14A30D07CD5 ON co_accounts (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_805CD14A5E237E06 ON co_accounts (name)');
        $this->addSql('CREATE TABLE co_account_urls (idAccounts INT NOT NULL, idUrls INT NOT NULL, PRIMARY KEY(idAccounts, idUrls))');
        $this->addSql('CREATE INDEX IDX_ADF18382996BB4F7 ON co_account_urls (idAccounts)');
        $this->addSql('CREATE INDEX IDX_ADF183825969693F ON co_account_urls (idUrls)');
        $this->addSql('CREATE TABLE co_account_phones (idAccounts INT NOT NULL, idPhones INT NOT NULL, PRIMARY KEY(idAccounts, idPhones))');
        $this->addSql('CREATE INDEX IDX_918DA964996BB4F7 ON co_account_phones (idAccounts)');
        $this->addSql('CREATE INDEX IDX_918DA9648039866F ON co_account_phones (idPhones)');
        $this->addSql('CREATE TABLE co_account_emails (idAccounts INT NOT NULL, idEmails INT NOT NULL, PRIMARY KEY(idAccounts, idEmails))');
        $this->addSql('CREATE INDEX IDX_3E246FC3996BB4F7 ON co_account_emails (idAccounts)');
        $this->addSql('CREATE INDEX IDX_3E246FC32F9040C8 ON co_account_emails (idEmails)');
        $this->addSql('CREATE TABLE co_account_notes (idAccounts INT NOT NULL, idNotes INT NOT NULL, PRIMARY KEY(idAccounts, idNotes))');
        $this->addSql('CREATE INDEX IDX_A3FBB24A996BB4F7 ON co_account_notes (idAccounts)');
        $this->addSql('CREATE INDEX IDX_A3FBB24A16DFE591 ON co_account_notes (idNotes)');
        $this->addSql('CREATE TABLE co_account_faxes (idAccounts INT NOT NULL, idFaxes INT NOT NULL, PRIMARY KEY(idAccounts, idFaxes))');
        $this->addSql('CREATE INDEX IDX_7A4E77DC996BB4F7 ON co_account_faxes (idAccounts)');
        $this->addSql('CREATE INDEX IDX_7A4E77DCCF6A2007 ON co_account_faxes (idFaxes)');
        $this->addSql('CREATE TABLE co_account_social_media_profiles (idAccounts INT NOT NULL, idSocialMediaProfiles INT NOT NULL, PRIMARY KEY(idAccounts, idSocialMediaProfiles))');
        $this->addSql('CREATE INDEX IDX_E06F75F5996BB4F7 ON co_account_social_media_profiles (idAccounts)');
        $this->addSql('CREATE INDEX IDX_E06F75F5573F8344 ON co_account_social_media_profiles (idSocialMediaProfiles)');
        $this->addSql('CREATE TABLE co_account_bank_accounts (idAccounts INT NOT NULL, idBankAccounts INT NOT NULL, PRIMARY KEY(idAccounts, idBankAccounts))');
        $this->addSql('CREATE INDEX IDX_C873A532996BB4F7 ON co_account_bank_accounts (idAccounts)');
        $this->addSql('CREATE INDEX IDX_C873A53237FCD1D8 ON co_account_bank_accounts (idBankAccounts)');
        $this->addSql('CREATE TABLE co_account_categories (idAccounts INT NOT NULL, idCategories INT NOT NULL, PRIMARY KEY(idAccounts, idCategories))');
        $this->addSql('CREATE INDEX IDX_B60E9510996BB4F7 ON co_account_categories (idAccounts)');
        $this->addSql('CREATE INDEX IDX_B60E9510B8075882 ON co_account_categories (idCategories)');
        $this->addSql('CREATE TABLE co_account_medias (idAccounts INT NOT NULL, idMedias INT NOT NULL, PRIMARY KEY(idAccounts, idMedias))');
        $this->addSql('CREATE INDEX IDX_60772810996BB4F7 ON co_account_medias (idAccounts)');
        $this->addSql('CREATE INDEX IDX_6077281071C3071B ON co_account_medias (idMedias)');
        $this->addSql('CREATE TABLE co_account_tags (idAccounts INT NOT NULL, idTags INT NOT NULL, PRIMARY KEY(idAccounts, idTags))');
        $this->addSql('CREATE INDEX IDX_E8D92005996BB4F7 ON co_account_tags (idAccounts)');
        $this->addSql('CREATE INDEX IDX_E8D920051C41CAB8 ON co_account_tags (idTags)');
        $this->addSql('CREATE TABLE co_address_types (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_addresses (id INT NOT NULL, title VARCHAR(250) DEFAULT NULL, primaryAddress BOOLEAN DEFAULT NULL, deliveryAddress BOOLEAN DEFAULT NULL, billingAddress BOOLEAN DEFAULT NULL, street VARCHAR(150) DEFAULT NULL, number VARCHAR(60) DEFAULT NULL, addition VARCHAR(60) DEFAULT NULL, zip VARCHAR(60) DEFAULT NULL, city VARCHAR(60) DEFAULT NULL, state VARCHAR(60) DEFAULT NULL, countryCode VARCHAR(5) DEFAULT NULL, postboxNumber VARCHAR(100) DEFAULT NULL, postboxPostcode VARCHAR(100) DEFAULT NULL, postboxCity VARCHAR(100) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, note TEXT DEFAULT NULL, idAdressTypes INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_26E9A6142A37021A ON co_addresses (idAdressTypes)');
        $this->addSql('CREATE TABLE co_bank_account (id INT NOT NULL, bankName VARCHAR(150) DEFAULT NULL, bic VARCHAR(100) DEFAULT NULL, iban VARCHAR(100) NOT NULL, public BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_contact_addresses (id INT NOT NULL, main BOOLEAN NOT NULL, idAddresses INT NOT NULL, idContacts INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DEE056893205E40 ON co_contact_addresses (idAddresses)');
        $this->addSql('CREATE INDEX IDX_DEE056860E33F28 ON co_contact_addresses (idContacts)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DEE056893205E4060E33F28 ON co_contact_addresses (idAddresses, idContacts)');
        $this->addSql('CREATE TABLE co_contact_locales (id INT NOT NULL, locale VARCHAR(60) NOT NULL, idContacts INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_31E5672760E33F28 ON co_contact_locales (idContacts)');
        $this->addSql('CREATE TABLE co_contact_titles (id INT NOT NULL, title VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4463FC02B36786B ON co_contact_titles (title)');
        $this->addSql('CREATE TABLE co_contacts (id INT NOT NULL, avatar INT DEFAULT NULL, firstName VARCHAR(60) NOT NULL, middleName VARCHAR(60) DEFAULT NULL, lastName VARCHAR(60) NOT NULL, birthday DATE DEFAULT NULL, salutation VARCHAR(255) DEFAULT NULL, formOfAddress INT DEFAULT NULL, newsletter BOOLEAN DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, note TEXT DEFAULT NULL, mainEmail VARCHAR(255) DEFAULT NULL, mainPhone VARCHAR(255) DEFAULT NULL, mainFax VARCHAR(255) DEFAULT NULL, mainUrl VARCHAR(255) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idTitles INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_79D45A95A254E939 ON co_contacts (idTitles)');
        $this->addSql('CREATE INDEX IDX_79D45A951677722F ON co_contacts (avatar)');
        $this->addSql('CREATE INDEX IDX_79D45A95DBF11E1D ON co_contacts (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_79D45A9530D07CD5 ON co_contacts (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_79D45A952392A156 ON co_contacts (firstName)');
        $this->addSql('CREATE INDEX IDX_79D45A9591161A88 ON co_contacts (lastName)');
        $this->addSql('CREATE TABLE co_contact_urls (idContacts INT NOT NULL, idUrls INT NOT NULL, PRIMARY KEY(idContacts, idUrls))');
        $this->addSql('CREATE INDEX IDX_99D86D760E33F28 ON co_contact_urls (idContacts)');
        $this->addSql('CREATE INDEX IDX_99D86D75969693F ON co_contact_urls (idUrls)');
        $this->addSql('CREATE TABLE co_contact_notes (idContacts INT NOT NULL, idNotes INT NOT NULL, PRIMARY KEY(idContacts, idNotes))');
        $this->addSql('CREATE INDEX IDX_B85E7B3460E33F28 ON co_contact_notes (idContacts)');
        $this->addSql('CREATE INDEX IDX_B85E7B3416DFE591 ON co_contact_notes (idNotes)');
        $this->addSql('CREATE TABLE co_contact_emails (idContacts INT NOT NULL, idEmails INT NOT NULL, PRIMARY KEY(idContacts, idEmails))');
        $this->addSql('CREATE INDEX IDX_8982963160E33F28 ON co_contact_emails (idContacts)');
        $this->addSql('CREATE INDEX IDX_898296312F9040C8 ON co_contact_emails (idEmails)');
        $this->addSql('CREATE TABLE co_contact_phones (idContacts INT NOT NULL, idPhones INT NOT NULL, PRIMARY KEY(idContacts, idPhones))');
        $this->addSql('CREATE INDEX IDX_262B509660E33F28 ON co_contact_phones (idContacts)');
        $this->addSql('CREATE INDEX IDX_262B50968039866F ON co_contact_phones (idPhones)');
        $this->addSql('CREATE TABLE co_contact_faxes (idContacts INT NOT NULL, idFaxes INT NOT NULL, PRIMARY KEY(idContacts, idFaxes))');
        $this->addSql('CREATE INDEX IDX_61EBBEA260E33F28 ON co_contact_faxes (idContacts)');
        $this->addSql('CREATE INDEX IDX_61EBBEA2CF6A2007 ON co_contact_faxes (idFaxes)');
        $this->addSql('CREATE TABLE co_contact_social_media_profiles (idContacts INT NOT NULL, idSocialMediaProfiles INT NOT NULL, PRIMARY KEY(idContacts, idSocialMediaProfiles))');
        $this->addSql('CREATE INDEX IDX_74FF4CC060E33F28 ON co_contact_social_media_profiles (idContacts)');
        $this->addSql('CREATE INDEX IDX_74FF4CC0573F8344 ON co_contact_social_media_profiles (idSocialMediaProfiles)');
        $this->addSql('CREATE TABLE co_contact_bank_accounts (idContacts INT NOT NULL, idBankAccounts INT NOT NULL, PRIMARY KEY(idContacts, idBankAccounts))');
        $this->addSql('CREATE INDEX IDX_76CDDA0660E33F28 ON co_contact_bank_accounts (idContacts)');
        $this->addSql('CREATE INDEX IDX_76CDDA0637FCD1D8 ON co_contact_bank_accounts (idBankAccounts)');
        $this->addSql('CREATE TABLE co_contact_medias (idContacts INT NOT NULL, idMedias INT NOT NULL, PRIMARY KEY(idContacts, idMedias))');
        $this->addSql('CREATE INDEX IDX_D7D1D1E260E33F28 ON co_contact_medias (idContacts)');
        $this->addSql('CREATE INDEX IDX_D7D1D1E271C3071B ON co_contact_medias (idMedias)');
        $this->addSql('CREATE TABLE co_contact_categories (idContacts INT NOT NULL, idCategories INT NOT NULL, PRIMARY KEY(idContacts, idCategories))');
        $this->addSql('CREATE INDEX IDX_8D2C3E2360E33F28 ON co_contact_categories (idContacts)');
        $this->addSql('CREATE INDEX IDX_8D2C3E23B8075882 ON co_contact_categories (idCategories)');
        $this->addSql('CREATE TABLE co_contact_tags (idContacts INT NOT NULL, idTags INT NOT NULL, PRIMARY KEY(idContacts, idTags))');
        $this->addSql('CREATE INDEX IDX_4CB5255060E33F28 ON co_contact_tags (idContacts)');
        $this->addSql('CREATE INDEX IDX_4CB525501C41CAB8 ON co_contact_tags (idTags)');
        $this->addSql('CREATE TABLE co_email_types (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_emails (id INT NOT NULL, email VARCHAR(60) NOT NULL, idEmailTypes INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A2F2CB77D816E840 ON co_emails (idEmailTypes)');
        $this->addSql('CREATE INDEX IDX_A2F2CB77E7927C74 ON co_emails (email)');
        $this->addSql('CREATE TABLE co_fax_types (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_faxes (id INT NOT NULL, fax VARCHAR(255) NOT NULL, idFaxTypes INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A5EC6A18B466C5DA ON co_faxes (idFaxTypes)');
        $this->addSql('CREATE TABLE co_notes (id INT NOT NULL, value TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_phone_types (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_phones (id INT NOT NULL, phone VARCHAR(60) NOT NULL, idPhoneTypes INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D5B0DD0A4249AD7 ON co_phones (idPhoneTypes)');
        $this->addSql('CREATE TABLE co_positions (id INT NOT NULL, position VARCHAR(191) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9FBC367E462CE4F5 ON co_positions (position)');
        $this->addSql('CREATE TABLE co_social_media_profile_types (id INT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_social_media_profiles (id INT NOT NULL, username VARCHAR(255) NOT NULL, idSocialMediaTypes INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DF585BFBB5BEA95F ON co_social_media_profiles (idSocialMediaTypes)');
        $this->addSql('CREATE TABLE co_url_types (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE co_urls (id INT NOT NULL, url VARCHAR(255) NOT NULL, idUrlTypes INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6F03842E882335CC ON co_urls (idUrlTypes)');
        $this->addSql('CREATE TABLE me_collection_meta (id INT NOT NULL, title VARCHAR(191) NOT NULL, description TEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, idCollections INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F8D5E71693782C96 ON me_collection_meta (idCollections)');
        $this->addSql('CREATE INDEX IDX_F8D5E7162B36786B ON me_collection_meta (title)');
        $this->addSql('CREATE INDEX IDX_F8D5E7164180C698 ON me_collection_meta (locale)');
        $this->addSql('CREATE TABLE me_collection_types (id INT NOT NULL, name VARCHAR(255) NOT NULL, collection_type_key VARCHAR(191) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB78DFB179078378 ON me_collection_types (collection_type_key)');
        $this->addSql('CREATE TABLE me_collections (id INT NOT NULL, style VARCHAR(255) DEFAULT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, collection_key VARCHAR(191) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idCollectionsMetaDefault INT DEFAULT NULL, idCollectionTypes INT NOT NULL, idCollectionsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F0D4887221904CD ON me_collections (collection_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F0D4887CFA3F467 ON me_collections (idCollectionsMetaDefault)');
        $this->addSql('CREATE INDEX IDX_F0D4887E67924D6 ON me_collections (idCollectionTypes)');
        $this->addSql('CREATE INDEX IDX_F0D4887A4F2DCF8 ON me_collections (idCollectionsParent)');
        $this->addSql('CREATE INDEX IDX_F0D4887DBF11E1D ON me_collections (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_F0D488730D07CD5 ON me_collections (idUsersChanger)');
        $this->addSql('CREATE TABLE me_file_version_content_languages (id INT NOT NULL, locale VARCHAR(5) NOT NULL, idFileVersions INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F3FD652C911ADE33 ON me_file_version_content_languages (idFileVersions)');
        $this->addSql('CREATE TABLE me_file_version_meta (id INT NOT NULL, title VARCHAR(191) NOT NULL, description TEXT DEFAULT NULL, copyright TEXT DEFAULT NULL, credits TEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, idFileVersions INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AD44B0AD911ADE33 ON me_file_version_meta (idFileVersions)');
        $this->addSql('CREATE INDEX IDX_AD44B0AD2B36786B ON me_file_version_meta (title)');
        $this->addSql('CREATE INDEX IDX_AD44B0AD4180C698 ON me_file_version_meta (locale)');
        $this->addSql('CREATE TABLE me_file_version_publish_languages (id INT NOT NULL, locale VARCHAR(5) NOT NULL, idFileVersions INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_195DAB3C911ADE33 ON me_file_version_publish_languages (idFileVersions)');
        $this->addSql('CREATE TABLE me_file_versions (id INT NOT NULL, name VARCHAR(191) NOT NULL, version INT NOT NULL, subVersion INT DEFAULT 0 NOT NULL, size INT NOT NULL, downloadCounter INT DEFAULT 0 NOT NULL, storageOptions TEXT DEFAULT NULL, mimeType VARCHAR(191) DEFAULT NULL, properties VARCHAR(1000) DEFAULT NULL, focusPointX INT DEFAULT NULL, focusPointY INT DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idFileVersionsMetaDefault INT DEFAULT NULL, idFiles INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B6E89456B801096 ON me_file_versions (idFileVersionsMetaDefault)');
        $this->addSql('CREATE INDEX IDX_7B6E894511F10344 ON me_file_versions (idFiles)');
        $this->addSql('CREATE INDEX IDX_7B6E8945DBF11E1D ON me_file_versions (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_7B6E894530D07CD5 ON me_file_versions (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_7B6E8945D8F2A087 ON me_file_versions (mimeType)');
        $this->addSql('CREATE INDEX IDX_7B6E8945F7C0246A ON me_file_versions (size)');
        $this->addSql('CREATE INDEX IDX_7B6E8945BF1CD3C3 ON me_file_versions (version)');
        $this->addSql('CREATE INDEX IDX_7B6E89455E237E06 ON me_file_versions (name)');
        $this->addSql('CREATE TABLE me_file_version_tags (idFileVersions INT NOT NULL, idTags INT NOT NULL, PRIMARY KEY(idFileVersions, idTags))');
        $this->addSql('CREATE INDEX IDX_150A30BE911ADE33 ON me_file_version_tags (idFileVersions)');
        $this->addSql('CREATE INDEX IDX_150A30BE1C41CAB8 ON me_file_version_tags (idTags)');
        $this->addSql('CREATE TABLE me_file_version_categories (idFileVersions INT NOT NULL, idCategories INT NOT NULL, PRIMARY KEY(idFileVersions, idCategories))');
        $this->addSql('CREATE INDEX IDX_2F1E17D0911ADE33 ON me_file_version_categories (idFileVersions)');
        $this->addSql('CREATE INDEX IDX_2F1E17D0B8075882 ON me_file_version_categories (idCategories)');
        $this->addSql('CREATE TABLE me_file_version_target_groups (idFileVersions INT NOT NULL, idTargetGroups INT NOT NULL, PRIMARY KEY(idFileVersions, idTargetGroups))');
        $this->addSql('CREATE INDEX IDX_4F3183AD911ADE33 ON me_file_version_target_groups (idFileVersions)');
        $this->addSql('CREATE INDEX IDX_4F3183AD9FCCEF27 ON me_file_version_target_groups (idTargetGroups)');
        $this->addSql('CREATE TABLE me_files (id INT NOT NULL, version INT NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idMedia INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CA8D04277DE8E211 ON me_files (idMedia)');
        $this->addSql('CREATE INDEX IDX_CA8D0427DBF11E1D ON me_files (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_CA8D042730D07CD5 ON me_files (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_CA8D0427BF1CD3C3 ON me_files (version)');
        $this->addSql('CREATE TABLE me_format_options (format_key VARCHAR(191) NOT NULL, crop_x INT NOT NULL, crop_y INT NOT NULL, crop_width INT NOT NULL, crop_height INT NOT NULL, fileVersion INT NOT NULL, PRIMARY KEY(format_key, fileVersion))');
        $this->addSql('CREATE INDEX IDX_6D25443B31852B63 ON me_format_options (fileVersion)');
        $this->addSql('CREATE TABLE me_media (id INT NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idMediaTypes INT NOT NULL, idPreviewImage INT DEFAULT NULL, idCollections INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A694E57284671716 ON me_media (idMediaTypes)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A694E572D1EB44DE ON me_media (idPreviewImage)');
        $this->addSql('CREATE INDEX IDX_A694E57293782C96 ON me_media (idCollections)');
        $this->addSql('CREATE INDEX IDX_A694E572DBF11E1D ON me_media (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_A694E57230D07CD5 ON me_media (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_A694E572A3F33DFA ON me_media (changed)');
        $this->addSql('CREATE INDEX IDX_A694E572B23DB7B8 ON me_media (created)');
        $this->addSql('CREATE TABLE me_media_types (id INT NOT NULL, name VARCHAR(191) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9A01D6E85E237E06 ON me_media_types (name)');
        $this->addSql('CREATE TABLE pr_preview_links (id INT NOT NULL, token VARCHAR(12) NOT NULL, resourceKey VARCHAR(255) NOT NULL, resourceId VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, options JSON NOT NULL, visitCount INT NOT NULL, lastVisit TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EFB5DBF25F37A13B ON pr_preview_links (token)');
        $this->addSql('COMMENT ON COLUMN pr_preview_links.lastVisit IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE ro_routes (id INT NOT NULL, target_id INT DEFAULT NULL, path VARCHAR(191) NOT NULL, locale VARCHAR(8) NOT NULL, entity_class VARCHAR(191) NOT NULL, entity_id VARCHAR(191) NOT NULL, history BOOLEAN NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_671DB7A4158E0B66 ON ro_routes (target_id)');
        $this->addSql('CREATE INDEX IDX_671DB7A4DBF11E1D ON ro_routes (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_671DB7A430D07CD5 ON ro_routes (idUsersChanger)');
        $this->addSql('CREATE INDEX IDX_671DB7A4B548B0F ON ro_routes (path)');
        $this->addSql('CREATE INDEX IDX_671DB7A44180C698 ON ro_routes (locale)');
        $this->addSql('CREATE INDEX idx_resource ON ro_routes (entity_id, entity_class)');
        $this->addSql('CREATE INDEX idx_history ON ro_routes (history)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_671DB7A4B548B0F4180C698 ON ro_routes (path, locale)');
        $this->addSql('CREATE TABLE se_access_controls (id INT NOT NULL, permissions SMALLINT NOT NULL, entityId VARCHAR(36) NOT NULL, entityClass VARCHAR(191) NOT NULL, entityIdInteger INT DEFAULT NULL, idRoles INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C526DC52A1FA6DDA ON se_access_controls (idRoles)');
        $this->addSql('CREATE INDEX IDX_C526DC52F62829FC ON se_access_controls (entityId)');
        $this->addSql('CREATE INDEX IDX_C526DC523963FFAB ON se_access_controls (entityClass)');
        $this->addSql('CREATE INDEX IDX_C526DC524473BB7A ON se_access_controls (entityIdInteger)');
        $this->addSql('CREATE TABLE se_groups (id INT NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, depth INT NOT NULL, name VARCHAR(60) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idGroupsParent INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_231E44ECBF274AB0 ON se_groups (idGroupsParent)');
        $this->addSql('CREATE INDEX IDX_231E44ECDBF11E1D ON se_groups (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_231E44EC30D07CD5 ON se_groups (idUsersChanger)');
        $this->addSql('CREATE TABLE se_group_roles (idGroups INT NOT NULL, idRoles INT NOT NULL, PRIMARY KEY(idGroups, idRoles))');
        $this->addSql('CREATE INDEX IDX_9713F725937C91EA ON se_group_roles (idGroups)');
        $this->addSql('CREATE INDEX IDX_9713F725A1FA6DDA ON se_group_roles (idRoles)');
        $this->addSql('CREATE TABLE se_permissions (id INT NOT NULL, context VARCHAR(191) NOT NULL, module VARCHAR(60) DEFAULT NULL, permissions SMALLINT NOT NULL, idRoles INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5CEC3EEAA1FA6DDA ON se_permissions (idRoles)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5CEC3EEAE25D857EC242628A1FA6DDA ON se_permissions (context, module, idRoles)');
        $this->addSql('CREATE TABLE se_role_settings (id INT NOT NULL, settingKey VARCHAR(191) NOT NULL, value JSON NOT NULL, roleId INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DAD1C8CBB8C2FD88 ON se_role_settings (roleId)');
        $this->addSql('CREATE INDEX IDX_DAD1C8CB3AA9950B ON se_role_settings (settingKey)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DAD1C8CB3AA9950BB8C2FD88 ON se_role_settings (settingKey, roleId)');
        $this->addSql('CREATE TABLE se_roles (id INT NOT NULL, name VARCHAR(60) NOT NULL, role_key VARCHAR(60) DEFAULT NULL, securitySystem VARCHAR(60) NOT NULL, anonymous BOOLEAN DEFAULT false NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idSecurityTypes INT DEFAULT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13B749A05E237E06 ON se_roles (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_13B749A03EF22FDB ON se_roles (role_key)');
        $this->addSql('CREATE INDEX IDX_13B749A0D02106C0 ON se_roles (idSecurityTypes)');
        $this->addSql('CREATE INDEX IDX_13B749A0DBF11E1D ON se_roles (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_13B749A030D07CD5 ON se_roles (idUsersChanger)');
        $this->addSql('CREATE TABLE se_security_types (id INT NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE se_user_groups (id INT NOT NULL, locale TEXT NOT NULL, idGroups INT DEFAULT NULL, idUsers INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E43ED0C8937C91EA ON se_user_groups (idGroups)');
        $this->addSql('CREATE INDEX IDX_E43ED0C8347E6F4 ON se_user_groups (idUsers)');
        $this->addSql('CREATE TABLE se_user_roles (id INT NOT NULL, locale TEXT NOT NULL, idUsers INT DEFAULT NULL, idRoles INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E48BD9DB347E6F4 ON se_user_roles (idUsers)');
        $this->addSql('CREATE INDEX IDX_E48BD9DBA1FA6DDA ON se_user_roles (idRoles)');
        $this->addSql('CREATE TABLE se_user_settings (settingsValue TEXT NOT NULL, settingsKey VARCHAR(150) NOT NULL, idUsers INT NOT NULL, PRIMARY KEY(settingsKey, idUsers))');
        $this->addSql('CREATE INDEX IDX_108FCAFA347E6F4 ON se_user_settings (idUsers)');
        $this->addSql('CREATE TABLE se_users (id INT NOT NULL, username VARCHAR(60) NOT NULL, password VARCHAR(128) NOT NULL, locale VARCHAR(60) NOT NULL, salt VARCHAR(60) NOT NULL, locked BOOLEAN DEFAULT false NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, lastLogin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmationKey VARCHAR(128) DEFAULT NULL, passwordResetToken VARCHAR(80) DEFAULT NULL, passwordResetTokenExpiresAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, passwordResetTokenEmailsSent INT DEFAULT 0, privateKey VARCHAR(2000) DEFAULT NULL, apiKey UUID DEFAULT NULL, email VARCHAR(191) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idContacts INT NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B10AC28EF85E0677 ON se_users (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B10AC28EADC1CD13 ON se_users (passwordResetToken)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B10AC28EE7927C74 ON se_users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B10AC28E60E33F28 ON se_users (idContacts)');
        $this->addSql('CREATE INDEX IDX_B10AC28EDBF11E1D ON se_users (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_B10AC28E30D07CD5 ON se_users (idUsersChanger)');
        $this->addSql('CREATE TABLE ta_tags (id INT NOT NULL, name VARCHAR(191) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, idUsersCreator INT DEFAULT NULL, idUsersChanger INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B258E4995E237E06 ON ta_tags (name)');
        $this->addSql('CREATE INDEX IDX_B258E499DBF11E1D ON ta_tags (idUsersCreator)');
        $this->addSql('CREATE INDEX IDX_B258E49930D07CD5 ON ta_tags (idUsersChanger)');
        $this->addSql('CREATE TABLE tr_trash_item_translations (id INT NOT NULL, locale VARCHAR(191) DEFAULT NULL, title VARCHAR(191) NOT NULL, trashItemId INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8264DAF45C8D7CA ON tr_trash_item_translations (trashItemId)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8264DAF45C8D7CA4180C698 ON tr_trash_item_translations (trashItemId, locale)');
        $this->addSql('CREATE TABLE tr_trash_items (id INT NOT NULL, resourceKey VARCHAR(191) NOT NULL, resourceId VARCHAR(191) NOT NULL, restoreData JSON NOT NULL, restoreType VARCHAR(191) DEFAULT NULL, restoreOptions JSON NOT NULL, resourceSecurityContext VARCHAR(191) DEFAULT NULL, resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, storeTimestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, defaultLocale VARCHAR(191) DEFAULT NULL, userId INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_102989B64B64DCC ON tr_trash_items (userId)');
        $this->addSql('CREATE INDEX IDX_102989B5DAEB55C8CF57CB1 ON tr_trash_items (resourceKey, resourceId)');
        $this->addSql('COMMENT ON COLUMN tr_trash_items.storeTimestamp IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE we_analytics (id INT NOT NULL, title VARCHAR(255) NOT NULL, webspace_key VARCHAR(191) NOT NULL, all_domains BOOLEAN NOT NULL, content JSON NOT NULL, type VARCHAR(60) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4E50BB8D1640EFD3 ON we_analytics (all_domains)');
        $this->addSql('CREATE INDEX IDX_4E50BB8DAE248174 ON we_analytics (webspace_key)');
        $this->addSql('CREATE TABLE we_analytics_domains (analytics INT NOT NULL, domain INT NOT NULL, PRIMARY KEY(analytics, domain))');
        $this->addSql('CREATE INDEX IDX_F9323B6EEAC2E688 ON we_analytics_domains (analytics)');
        $this->addSql('CREATE INDEX IDX_F9323B6EA7A91E0B ON we_analytics_domains (domain)');
        $this->addSql('CREATE TABLE we_domains (id INT NOT NULL, url VARCHAR(191) NOT NULL, environment VARCHAR(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CFAB3F5F47645AE ON we_domains (url)');
        $this->addSql('CREATE INDEX IDX_7CFAB3F54626DE22 ON we_domains (environment)');
        $this->addSql('CREATE TABLE phpcr_namespaces (prefix VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL, PRIMARY KEY(prefix))');
        $this->addSql('CREATE TABLE phpcr_workspaces (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE phpcr_nodes (id SERIAL NOT NULL, path VARCHAR(255) NOT NULL, parent VARCHAR(255) NOT NULL, local_name VARCHAR(255) NOT NULL, namespace VARCHAR(255) NOT NULL, workspace_name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, props TEXT NOT NULL, numerical_props TEXT DEFAULT NULL, depth INT NOT NULL, sort_order INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4624AD7B548B0F1AC10DC4 ON phpcr_nodes (path, workspace_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4624AD7772E836A1AC10DC4 ON phpcr_nodes (identifier, workspace_name)');
        $this->addSql('CREATE INDEX IDX_A4624AD73D8E604F ON phpcr_nodes (parent)');
        $this->addSql('CREATE INDEX IDX_A4624AD78CDE5729 ON phpcr_nodes (type)');
        $this->addSql('CREATE INDEX IDX_A4624AD7623C14D533E16B56 ON phpcr_nodes (local_name, namespace)');
        $this->addSql('CREATE TABLE phpcr_internal_index_types (type VARCHAR(255) NOT NULL, node_id INT NOT NULL, PRIMARY KEY(type, node_id))');
        $this->addSql('CREATE TABLE phpcr_binarydata (id SERIAL NOT NULL, node_id INT NOT NULL, property_name VARCHAR(255) NOT NULL, workspace_name VARCHAR(255) NOT NULL, idx INT DEFAULT 0 NOT NULL, data BYTEA NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_37E65615460D9FD7413BC13C1AC10DC4E7087E10 ON phpcr_binarydata (node_id, property_name, workspace_name, idx)');
        $this->addSql('CREATE TABLE phpcr_nodes_references (source_id INT NOT NULL, source_property_name VARCHAR(220) NOT NULL, target_id INT NOT NULL, PRIMARY KEY(source_id, source_property_name, target_id))');
        $this->addSql('CREATE INDEX IDX_F3BF7E1158E0B66 ON phpcr_nodes_references (target_id)');
        $this->addSql('CREATE TABLE phpcr_nodes_weakreferences (source_id INT NOT NULL, source_property_name VARCHAR(220) NOT NULL, target_id INT NOT NULL, PRIMARY KEY(source_id, source_property_name, target_id))');
        $this->addSql('CREATE INDEX IDX_F0E4F6FA158E0B66 ON phpcr_nodes_weakreferences (target_id)');
        $this->addSql('CREATE TABLE phpcr_type_nodes (node_type_id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, supertypes VARCHAR(255) NOT NULL, is_abstract BOOLEAN NOT NULL, is_mixin BOOLEAN NOT NULL, queryable BOOLEAN NOT NULL, orderable_child_nodes BOOLEAN NOT NULL, primary_item VARCHAR(255) DEFAULT NULL, PRIMARY KEY(node_type_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34B0A8095E237E06 ON phpcr_type_nodes (name)');
        $this->addSql('CREATE TABLE phpcr_type_props (node_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, protected BOOLEAN NOT NULL, auto_created BOOLEAN NOT NULL, mandatory BOOLEAN NOT NULL, on_parent_version INT NOT NULL, multiple BOOLEAN NOT NULL, fulltext_searchable BOOLEAN NOT NULL, query_orderable BOOLEAN NOT NULL, required_type INT NOT NULL, query_operators INT NOT NULL, default_value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(node_type_id, name))');
        $this->addSql('CREATE TABLE phpcr_type_childs (id SERIAL NOT NULL, node_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, protected BOOLEAN NOT NULL, auto_created BOOLEAN NOT NULL, mandatory BOOLEAN NOT NULL, on_parent_version INT NOT NULL, primary_types VARCHAR(255) NOT NULL, default_type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE ac_activities ADD CONSTRAINT FK_3EE015D064B64DCC FOREIGN KEY (userId) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE at_target_group_conditions ADD CONSTRAINT FK_94078B9989EB12AB FOREIGN KEY (idTargetGroupRules) REFERENCES at_target_group_rules (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE at_target_group_rules ADD CONSTRAINT FK_189AEDAD9FCCEF27 FOREIGN KEY (idTargetGroups) REFERENCES at_target_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE at_target_group_webspaces ADD CONSTRAINT FK_4B0C69E59FCCEF27 FOREIGN KEY (idTargetGroups) REFERENCES at_target_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D78937A3C3B1 FOREIGN KEY (idCategoriesParent) REFERENCES ca_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D789DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_categories ADD CONSTRAINT FK_3D85D78930D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_meta ADD CONSTRAINT FK_2575BBB0B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translation_medias ADD CONSTRAINT FK_39FC41BA17CA14DA FOREIGN KEY (idCategoryTranslations) REFERENCES ca_category_translations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translation_medias ADD CONSTRAINT FK_39FC41BA7DE8E211 FOREIGN KEY (idMedia) REFERENCES me_media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E3B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E3DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translations ADD CONSTRAINT FK_5DCED5E330D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_keywords ADD CONSTRAINT FK_FE02CA0BDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_keywords ADD CONSTRAINT FK_FE02CA0B30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translation_keywords ADD CONSTRAINT FK_D15FBE37F9FC9F05 FOREIGN KEY (idKeywords) REFERENCES ca_keywords (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ca_category_translation_keywords ADD CONSTRAINT FK_D15FBE3717CA14DA FOREIGN KEY (idCategoryTranslations) REFERENCES ca_category_translations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_addresses ADD CONSTRAINT FK_4165FE4893205E40 FOREIGN KEY (idAddresses) REFERENCES co_addresses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_addresses ADD CONSTRAINT FK_4165FE48996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E2A75CE2A FOREIGN KEY (idPositions) REFERENCES co_positions (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E60E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_contacts ADD CONSTRAINT FK_28C6CA0E996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14A6D4A8651 FOREIGN KEY (idContactsMain) REFERENCES co_contacts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14AC9171171 FOREIGN KEY (idAccountsParent) REFERENCES co_accounts (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14AE48E9A13 FOREIGN KEY (logo) REFERENCES me_media (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14ADBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_accounts ADD CONSTRAINT FK_805CD14A30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_urls ADD CONSTRAINT FK_ADF18382996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_urls ADD CONSTRAINT FK_ADF183825969693F FOREIGN KEY (idUrls) REFERENCES co_urls (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_phones ADD CONSTRAINT FK_918DA964996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_phones ADD CONSTRAINT FK_918DA9648039866F FOREIGN KEY (idPhones) REFERENCES co_phones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_emails ADD CONSTRAINT FK_3E246FC3996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_emails ADD CONSTRAINT FK_3E246FC32F9040C8 FOREIGN KEY (idEmails) REFERENCES co_emails (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_notes ADD CONSTRAINT FK_A3FBB24A996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_notes ADD CONSTRAINT FK_A3FBB24A16DFE591 FOREIGN KEY (idNotes) REFERENCES co_notes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_faxes ADD CONSTRAINT FK_7A4E77DC996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_faxes ADD CONSTRAINT FK_7A4E77DCCF6A2007 FOREIGN KEY (idFaxes) REFERENCES co_faxes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_social_media_profiles ADD CONSTRAINT FK_E06F75F5996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_social_media_profiles ADD CONSTRAINT FK_E06F75F5573F8344 FOREIGN KEY (idSocialMediaProfiles) REFERENCES co_social_media_profiles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_bank_accounts ADD CONSTRAINT FK_C873A532996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_bank_accounts ADD CONSTRAINT FK_C873A53237FCD1D8 FOREIGN KEY (idBankAccounts) REFERENCES co_bank_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_categories ADD CONSTRAINT FK_B60E9510996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_categories ADD CONSTRAINT FK_B60E9510B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_medias ADD CONSTRAINT FK_60772810996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_medias ADD CONSTRAINT FK_6077281071C3071B FOREIGN KEY (idMedias) REFERENCES me_media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_tags ADD CONSTRAINT FK_E8D92005996BB4F7 FOREIGN KEY (idAccounts) REFERENCES co_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_account_tags ADD CONSTRAINT FK_E8D920051C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_addresses ADD CONSTRAINT FK_26E9A6142A37021A FOREIGN KEY (idAdressTypes) REFERENCES co_address_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_addresses ADD CONSTRAINT FK_DEE056893205E40 FOREIGN KEY (idAddresses) REFERENCES co_addresses (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_addresses ADD CONSTRAINT FK_DEE056860E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_locales ADD CONSTRAINT FK_31E5672760E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A95A254E939 FOREIGN KEY (idTitles) REFERENCES co_contact_titles (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A951677722F FOREIGN KEY (avatar) REFERENCES me_media (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A95DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contacts ADD CONSTRAINT FK_79D45A9530D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_urls ADD CONSTRAINT FK_99D86D760E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_urls ADD CONSTRAINT FK_99D86D75969693F FOREIGN KEY (idUrls) REFERENCES co_urls (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_notes ADD CONSTRAINT FK_B85E7B3460E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_notes ADD CONSTRAINT FK_B85E7B3416DFE591 FOREIGN KEY (idNotes) REFERENCES co_notes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_emails ADD CONSTRAINT FK_8982963160E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_emails ADD CONSTRAINT FK_898296312F9040C8 FOREIGN KEY (idEmails) REFERENCES co_emails (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_phones ADD CONSTRAINT FK_262B509660E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_phones ADD CONSTRAINT FK_262B50968039866F FOREIGN KEY (idPhones) REFERENCES co_phones (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_faxes ADD CONSTRAINT FK_61EBBEA260E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_faxes ADD CONSTRAINT FK_61EBBEA2CF6A2007 FOREIGN KEY (idFaxes) REFERENCES co_faxes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles ADD CONSTRAINT FK_74FF4CC060E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles ADD CONSTRAINT FK_74FF4CC0573F8344 FOREIGN KEY (idSocialMediaProfiles) REFERENCES co_social_media_profiles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_bank_accounts ADD CONSTRAINT FK_76CDDA0660E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_bank_accounts ADD CONSTRAINT FK_76CDDA0637FCD1D8 FOREIGN KEY (idBankAccounts) REFERENCES co_bank_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_medias ADD CONSTRAINT FK_D7D1D1E260E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_medias ADD CONSTRAINT FK_D7D1D1E271C3071B FOREIGN KEY (idMedias) REFERENCES me_media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_categories ADD CONSTRAINT FK_8D2C3E2360E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_categories ADD CONSTRAINT FK_8D2C3E23B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_tags ADD CONSTRAINT FK_4CB5255060E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_contact_tags ADD CONSTRAINT FK_4CB525501C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_emails ADD CONSTRAINT FK_A2F2CB77D816E840 FOREIGN KEY (idEmailTypes) REFERENCES co_email_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_faxes ADD CONSTRAINT FK_A5EC6A18B466C5DA FOREIGN KEY (idFaxTypes) REFERENCES co_fax_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_phones ADD CONSTRAINT FK_D5B0DD0A4249AD7 FOREIGN KEY (idPhoneTypes) REFERENCES co_phone_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_social_media_profiles ADD CONSTRAINT FK_DF585BFBB5BEA95F FOREIGN KEY (idSocialMediaTypes) REFERENCES co_social_media_profile_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE co_urls ADD CONSTRAINT FK_6F03842E882335CC FOREIGN KEY (idUrlTypes) REFERENCES co_url_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_collection_meta ADD CONSTRAINT FK_F8D5E71693782C96 FOREIGN KEY (idCollections) REFERENCES me_collections (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887CFA3F467 FOREIGN KEY (idCollectionsMetaDefault) REFERENCES me_collection_meta (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887E67924D6 FOREIGN KEY (idCollectionTypes) REFERENCES me_collection_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887A4F2DCF8 FOREIGN KEY (idCollectionsParent) REFERENCES me_collections (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D4887DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_collections ADD CONSTRAINT FK_F0D488730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_content_languages ADD CONSTRAINT FK_F3FD652C911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_meta ADD CONSTRAINT FK_AD44B0AD911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_publish_languages ADD CONSTRAINT FK_195DAB3C911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E89456B801096 FOREIGN KEY (idFileVersionsMetaDefault) REFERENCES me_file_version_meta (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E894511F10344 FOREIGN KEY (idFiles) REFERENCES me_files (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E8945DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_versions ADD CONSTRAINT FK_7B6E894530D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_tags ADD CONSTRAINT FK_150A30BE911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_tags ADD CONSTRAINT FK_150A30BE1C41CAB8 FOREIGN KEY (idTags) REFERENCES ta_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_categories ADD CONSTRAINT FK_2F1E17D0911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_categories ADD CONSTRAINT FK_2F1E17D0B8075882 FOREIGN KEY (idCategories) REFERENCES ca_categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_target_groups ADD CONSTRAINT FK_4F3183AD911ADE33 FOREIGN KEY (idFileVersions) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_file_version_target_groups ADD CONSTRAINT FK_4F3183AD9FCCEF27 FOREIGN KEY (idTargetGroups) REFERENCES at_target_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D04277DE8E211 FOREIGN KEY (idMedia) REFERENCES me_media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D0427DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_files ADD CONSTRAINT FK_CA8D042730D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_format_options ADD CONSTRAINT FK_6D25443B31852B63 FOREIGN KEY (fileVersion) REFERENCES me_file_versions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57284671716 FOREIGN KEY (idMediaTypes) REFERENCES me_media_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E572D1EB44DE FOREIGN KEY (idPreviewImage) REFERENCES me_media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57293782C96 FOREIGN KEY (idCollections) REFERENCES me_collections (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E572DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE me_media ADD CONSTRAINT FK_A694E57230D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A4158E0B66 FOREIGN KEY (target_id) REFERENCES ro_routes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A4DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ro_routes ADD CONSTRAINT FK_671DB7A430D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_access_controls ADD CONSTRAINT FK_C526DC52A1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_groups ADD CONSTRAINT FK_231E44ECBF274AB0 FOREIGN KEY (idGroupsParent) REFERENCES se_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_groups ADD CONSTRAINT FK_231E44ECDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_groups ADD CONSTRAINT FK_231E44EC30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_group_roles ADD CONSTRAINT FK_9713F725937C91EA FOREIGN KEY (idGroups) REFERENCES se_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_group_roles ADD CONSTRAINT FK_9713F725A1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_permissions ADD CONSTRAINT FK_5CEC3EEAA1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_role_settings ADD CONSTRAINT FK_DAD1C8CBB8C2FD88 FOREIGN KEY (roleId) REFERENCES se_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A0D02106C0 FOREIGN KEY (idSecurityTypes) REFERENCES se_security_types (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A0DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_roles ADD CONSTRAINT FK_13B749A030D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_user_groups ADD CONSTRAINT FK_E43ED0C8937C91EA FOREIGN KEY (idGroups) REFERENCES se_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_user_groups ADD CONSTRAINT FK_E43ED0C8347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_user_roles ADD CONSTRAINT FK_E48BD9DB347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_user_roles ADD CONSTRAINT FK_E48BD9DBA1FA6DDA FOREIGN KEY (idRoles) REFERENCES se_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_user_settings ADD CONSTRAINT FK_108FCAFA347E6F4 FOREIGN KEY (idUsers) REFERENCES se_users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28E60E33F28 FOREIGN KEY (idContacts) REFERENCES co_contacts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28EDBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE se_users ADD CONSTRAINT FK_B10AC28E30D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ta_tags ADD CONSTRAINT FK_B258E499DBF11E1D FOREIGN KEY (idUsersCreator) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ta_tags ADD CONSTRAINT FK_B258E49930D07CD5 FOREIGN KEY (idUsersChanger) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tr_trash_item_translations ADD CONSTRAINT FK_8264DAF45C8D7CA FOREIGN KEY (trashItemId) REFERENCES tr_trash_items (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tr_trash_items ADD CONSTRAINT FK_102989B64B64DCC FOREIGN KEY (userId) REFERENCES se_users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE we_analytics_domains ADD CONSTRAINT FK_F9323B6EEAC2E688 FOREIGN KEY (analytics) REFERENCES we_analytics (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE we_analytics_domains ADD CONSTRAINT FK_F9323B6EA7A91E0B FOREIGN KEY (domain) REFERENCES we_domains (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->skipIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQL100Platform,
            "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\PostgreSQL100Platform'."
        );

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE ac_activities_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE at_target_group_conditions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE at_target_group_rules_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE at_target_group_webspaces_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE at_target_groups_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ca_categories_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ca_category_meta_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ca_category_translation_medias_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ca_category_translations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ca_keywords_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_account_addresses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_account_contacts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_accounts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_address_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_addresses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_bank_account_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_contact_addresses_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_contact_locales_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_contact_titles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_contacts_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_email_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_emails_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_fax_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_faxes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_notes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_phone_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_phones_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_positions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_social_media_profile_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_social_media_profiles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_url_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE co_urls_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_collection_meta_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_collection_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_collections_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_file_version_content_languages_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_file_version_meta_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_file_version_publish_languages_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_file_versions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_files_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_media_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE me_media_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pr_preview_links_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ro_routes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_access_controls_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_groups_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_permissions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_role_settings_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_roles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_security_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_user_groups_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_user_roles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE se_users_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ta_tags_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tr_trash_item_translations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tr_trash_items_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE we_analytics_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE we_domains_id_seq CASCADE');
        $this->addSql('ALTER TABLE ac_activities DROP CONSTRAINT FK_3EE015D064B64DCC');
        $this->addSql('ALTER TABLE at_target_group_conditions DROP CONSTRAINT FK_94078B9989EB12AB');
        $this->addSql('ALTER TABLE at_target_group_rules DROP CONSTRAINT FK_189AEDAD9FCCEF27');
        $this->addSql('ALTER TABLE at_target_group_webspaces DROP CONSTRAINT FK_4B0C69E59FCCEF27');
        $this->addSql('ALTER TABLE ca_categories DROP CONSTRAINT FK_3D85D78937A3C3B1');
        $this->addSql('ALTER TABLE ca_categories DROP CONSTRAINT FK_3D85D789DBF11E1D');
        $this->addSql('ALTER TABLE ca_categories DROP CONSTRAINT FK_3D85D78930D07CD5');
        $this->addSql('ALTER TABLE ca_category_meta DROP CONSTRAINT FK_2575BBB0B8075882');
        $this->addSql('ALTER TABLE ca_category_translation_medias DROP CONSTRAINT FK_39FC41BA17CA14DA');
        $this->addSql('ALTER TABLE ca_category_translation_medias DROP CONSTRAINT FK_39FC41BA7DE8E211');
        $this->addSql('ALTER TABLE ca_category_translations DROP CONSTRAINT FK_5DCED5E3B8075882');
        $this->addSql('ALTER TABLE ca_category_translations DROP CONSTRAINT FK_5DCED5E3DBF11E1D');
        $this->addSql('ALTER TABLE ca_category_translations DROP CONSTRAINT FK_5DCED5E330D07CD5');
        $this->addSql('ALTER TABLE ca_keywords DROP CONSTRAINT FK_FE02CA0BDBF11E1D');
        $this->addSql('ALTER TABLE ca_keywords DROP CONSTRAINT FK_FE02CA0B30D07CD5');
        $this->addSql('ALTER TABLE ca_category_translation_keywords DROP CONSTRAINT FK_D15FBE37F9FC9F05');
        $this->addSql('ALTER TABLE ca_category_translation_keywords DROP CONSTRAINT FK_D15FBE3717CA14DA');
        $this->addSql('ALTER TABLE co_account_addresses DROP CONSTRAINT FK_4165FE4893205E40');
        $this->addSql('ALTER TABLE co_account_addresses DROP CONSTRAINT FK_4165FE48996BB4F7');
        $this->addSql('ALTER TABLE co_account_contacts DROP CONSTRAINT FK_28C6CA0E2A75CE2A');
        $this->addSql('ALTER TABLE co_account_contacts DROP CONSTRAINT FK_28C6CA0E60E33F28');
        $this->addSql('ALTER TABLE co_account_contacts DROP CONSTRAINT FK_28C6CA0E996BB4F7');
        $this->addSql('ALTER TABLE co_accounts DROP CONSTRAINT FK_805CD14A6D4A8651');
        $this->addSql('ALTER TABLE co_accounts DROP CONSTRAINT FK_805CD14AC9171171');
        $this->addSql('ALTER TABLE co_accounts DROP CONSTRAINT FK_805CD14AE48E9A13');
        $this->addSql('ALTER TABLE co_accounts DROP CONSTRAINT FK_805CD14ADBF11E1D');
        $this->addSql('ALTER TABLE co_accounts DROP CONSTRAINT FK_805CD14A30D07CD5');
        $this->addSql('ALTER TABLE co_account_urls DROP CONSTRAINT FK_ADF18382996BB4F7');
        $this->addSql('ALTER TABLE co_account_urls DROP CONSTRAINT FK_ADF183825969693F');
        $this->addSql('ALTER TABLE co_account_phones DROP CONSTRAINT FK_918DA964996BB4F7');
        $this->addSql('ALTER TABLE co_account_phones DROP CONSTRAINT FK_918DA9648039866F');
        $this->addSql('ALTER TABLE co_account_emails DROP CONSTRAINT FK_3E246FC3996BB4F7');
        $this->addSql('ALTER TABLE co_account_emails DROP CONSTRAINT FK_3E246FC32F9040C8');
        $this->addSql('ALTER TABLE co_account_notes DROP CONSTRAINT FK_A3FBB24A996BB4F7');
        $this->addSql('ALTER TABLE co_account_notes DROP CONSTRAINT FK_A3FBB24A16DFE591');
        $this->addSql('ALTER TABLE co_account_faxes DROP CONSTRAINT FK_7A4E77DC996BB4F7');
        $this->addSql('ALTER TABLE co_account_faxes DROP CONSTRAINT FK_7A4E77DCCF6A2007');
        $this->addSql('ALTER TABLE co_account_social_media_profiles DROP CONSTRAINT FK_E06F75F5996BB4F7');
        $this->addSql('ALTER TABLE co_account_social_media_profiles DROP CONSTRAINT FK_E06F75F5573F8344');
        $this->addSql('ALTER TABLE co_account_bank_accounts DROP CONSTRAINT FK_C873A532996BB4F7');
        $this->addSql('ALTER TABLE co_account_bank_accounts DROP CONSTRAINT FK_C873A53237FCD1D8');
        $this->addSql('ALTER TABLE co_account_categories DROP CONSTRAINT FK_B60E9510996BB4F7');
        $this->addSql('ALTER TABLE co_account_categories DROP CONSTRAINT FK_B60E9510B8075882');
        $this->addSql('ALTER TABLE co_account_medias DROP CONSTRAINT FK_60772810996BB4F7');
        $this->addSql('ALTER TABLE co_account_medias DROP CONSTRAINT FK_6077281071C3071B');
        $this->addSql('ALTER TABLE co_account_tags DROP CONSTRAINT FK_E8D92005996BB4F7');
        $this->addSql('ALTER TABLE co_account_tags DROP CONSTRAINT FK_E8D920051C41CAB8');
        $this->addSql('ALTER TABLE co_addresses DROP CONSTRAINT FK_26E9A6142A37021A');
        $this->addSql('ALTER TABLE co_contact_addresses DROP CONSTRAINT FK_DEE056893205E40');
        $this->addSql('ALTER TABLE co_contact_addresses DROP CONSTRAINT FK_DEE056860E33F28');
        $this->addSql('ALTER TABLE co_contact_locales DROP CONSTRAINT FK_31E5672760E33F28');
        $this->addSql('ALTER TABLE co_contacts DROP CONSTRAINT FK_79D45A95A254E939');
        $this->addSql('ALTER TABLE co_contacts DROP CONSTRAINT FK_79D45A951677722F');
        $this->addSql('ALTER TABLE co_contacts DROP CONSTRAINT FK_79D45A95DBF11E1D');
        $this->addSql('ALTER TABLE co_contacts DROP CONSTRAINT FK_79D45A9530D07CD5');
        $this->addSql('ALTER TABLE co_contact_urls DROP CONSTRAINT FK_99D86D760E33F28');
        $this->addSql('ALTER TABLE co_contact_urls DROP CONSTRAINT FK_99D86D75969693F');
        $this->addSql('ALTER TABLE co_contact_notes DROP CONSTRAINT FK_B85E7B3460E33F28');
        $this->addSql('ALTER TABLE co_contact_notes DROP CONSTRAINT FK_B85E7B3416DFE591');
        $this->addSql('ALTER TABLE co_contact_emails DROP CONSTRAINT FK_8982963160E33F28');
        $this->addSql('ALTER TABLE co_contact_emails DROP CONSTRAINT FK_898296312F9040C8');
        $this->addSql('ALTER TABLE co_contact_phones DROP CONSTRAINT FK_262B509660E33F28');
        $this->addSql('ALTER TABLE co_contact_phones DROP CONSTRAINT FK_262B50968039866F');
        $this->addSql('ALTER TABLE co_contact_faxes DROP CONSTRAINT FK_61EBBEA260E33F28');
        $this->addSql('ALTER TABLE co_contact_faxes DROP CONSTRAINT FK_61EBBEA2CF6A2007');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles DROP CONSTRAINT FK_74FF4CC060E33F28');
        $this->addSql('ALTER TABLE co_contact_social_media_profiles DROP CONSTRAINT FK_74FF4CC0573F8344');
        $this->addSql('ALTER TABLE co_contact_bank_accounts DROP CONSTRAINT FK_76CDDA0660E33F28');
        $this->addSql('ALTER TABLE co_contact_bank_accounts DROP CONSTRAINT FK_76CDDA0637FCD1D8');
        $this->addSql('ALTER TABLE co_contact_medias DROP CONSTRAINT FK_D7D1D1E260E33F28');
        $this->addSql('ALTER TABLE co_contact_medias DROP CONSTRAINT FK_D7D1D1E271C3071B');
        $this->addSql('ALTER TABLE co_contact_categories DROP CONSTRAINT FK_8D2C3E2360E33F28');
        $this->addSql('ALTER TABLE co_contact_categories DROP CONSTRAINT FK_8D2C3E23B8075882');
        $this->addSql('ALTER TABLE co_contact_tags DROP CONSTRAINT FK_4CB5255060E33F28');
        $this->addSql('ALTER TABLE co_contact_tags DROP CONSTRAINT FK_4CB525501C41CAB8');
        $this->addSql('ALTER TABLE co_emails DROP CONSTRAINT FK_A2F2CB77D816E840');
        $this->addSql('ALTER TABLE co_faxes DROP CONSTRAINT FK_A5EC6A18B466C5DA');
        $this->addSql('ALTER TABLE co_phones DROP CONSTRAINT FK_D5B0DD0A4249AD7');
        $this->addSql('ALTER TABLE co_social_media_profiles DROP CONSTRAINT FK_DF585BFBB5BEA95F');
        $this->addSql('ALTER TABLE co_urls DROP CONSTRAINT FK_6F03842E882335CC');
        $this->addSql('ALTER TABLE me_collection_meta DROP CONSTRAINT FK_F8D5E71693782C96');
        $this->addSql('ALTER TABLE me_collections DROP CONSTRAINT FK_F0D4887CFA3F467');
        $this->addSql('ALTER TABLE me_collections DROP CONSTRAINT FK_F0D4887E67924D6');
        $this->addSql('ALTER TABLE me_collections DROP CONSTRAINT FK_F0D4887A4F2DCF8');
        $this->addSql('ALTER TABLE me_collections DROP CONSTRAINT FK_F0D4887DBF11E1D');
        $this->addSql('ALTER TABLE me_collections DROP CONSTRAINT FK_F0D488730D07CD5');
        $this->addSql('ALTER TABLE me_file_version_content_languages DROP CONSTRAINT FK_F3FD652C911ADE33');
        $this->addSql('ALTER TABLE me_file_version_meta DROP CONSTRAINT FK_AD44B0AD911ADE33');
        $this->addSql('ALTER TABLE me_file_version_publish_languages DROP CONSTRAINT FK_195DAB3C911ADE33');
        $this->addSql('ALTER TABLE me_file_versions DROP CONSTRAINT FK_7B6E89456B801096');
        $this->addSql('ALTER TABLE me_file_versions DROP CONSTRAINT FK_7B6E894511F10344');
        $this->addSql('ALTER TABLE me_file_versions DROP CONSTRAINT FK_7B6E8945DBF11E1D');
        $this->addSql('ALTER TABLE me_file_versions DROP CONSTRAINT FK_7B6E894530D07CD5');
        $this->addSql('ALTER TABLE me_file_version_tags DROP CONSTRAINT FK_150A30BE911ADE33');
        $this->addSql('ALTER TABLE me_file_version_tags DROP CONSTRAINT FK_150A30BE1C41CAB8');
        $this->addSql('ALTER TABLE me_file_version_categories DROP CONSTRAINT FK_2F1E17D0911ADE33');
        $this->addSql('ALTER TABLE me_file_version_categories DROP CONSTRAINT FK_2F1E17D0B8075882');
        $this->addSql('ALTER TABLE me_file_version_target_groups DROP CONSTRAINT FK_4F3183AD911ADE33');
        $this->addSql('ALTER TABLE me_file_version_target_groups DROP CONSTRAINT FK_4F3183AD9FCCEF27');
        $this->addSql('ALTER TABLE me_files DROP CONSTRAINT FK_CA8D04277DE8E211');
        $this->addSql('ALTER TABLE me_files DROP CONSTRAINT FK_CA8D0427DBF11E1D');
        $this->addSql('ALTER TABLE me_files DROP CONSTRAINT FK_CA8D042730D07CD5');
        $this->addSql('ALTER TABLE me_format_options DROP CONSTRAINT FK_6D25443B31852B63');
        $this->addSql('ALTER TABLE me_media DROP CONSTRAINT FK_A694E57284671716');
        $this->addSql('ALTER TABLE me_media DROP CONSTRAINT FK_A694E572D1EB44DE');
        $this->addSql('ALTER TABLE me_media DROP CONSTRAINT FK_A694E57293782C96');
        $this->addSql('ALTER TABLE me_media DROP CONSTRAINT FK_A694E572DBF11E1D');
        $this->addSql('ALTER TABLE me_media DROP CONSTRAINT FK_A694E57230D07CD5');
        $this->addSql('ALTER TABLE ro_routes DROP CONSTRAINT FK_671DB7A4158E0B66');
        $this->addSql('ALTER TABLE ro_routes DROP CONSTRAINT FK_671DB7A4DBF11E1D');
        $this->addSql('ALTER TABLE ro_routes DROP CONSTRAINT FK_671DB7A430D07CD5');
        $this->addSql('ALTER TABLE se_access_controls DROP CONSTRAINT FK_C526DC52A1FA6DDA');
        $this->addSql('ALTER TABLE se_groups DROP CONSTRAINT FK_231E44ECBF274AB0');
        $this->addSql('ALTER TABLE se_groups DROP CONSTRAINT FK_231E44ECDBF11E1D');
        $this->addSql('ALTER TABLE se_groups DROP CONSTRAINT FK_231E44EC30D07CD5');
        $this->addSql('ALTER TABLE se_group_roles DROP CONSTRAINT FK_9713F725937C91EA');
        $this->addSql('ALTER TABLE se_group_roles DROP CONSTRAINT FK_9713F725A1FA6DDA');
        $this->addSql('ALTER TABLE se_permissions DROP CONSTRAINT FK_5CEC3EEAA1FA6DDA');
        $this->addSql('ALTER TABLE se_role_settings DROP CONSTRAINT FK_DAD1C8CBB8C2FD88');
        $this->addSql('ALTER TABLE se_roles DROP CONSTRAINT FK_13B749A0D02106C0');
        $this->addSql('ALTER TABLE se_roles DROP CONSTRAINT FK_13B749A0DBF11E1D');
        $this->addSql('ALTER TABLE se_roles DROP CONSTRAINT FK_13B749A030D07CD5');
        $this->addSql('ALTER TABLE se_user_groups DROP CONSTRAINT FK_E43ED0C8937C91EA');
        $this->addSql('ALTER TABLE se_user_groups DROP CONSTRAINT FK_E43ED0C8347E6F4');
        $this->addSql('ALTER TABLE se_user_roles DROP CONSTRAINT FK_E48BD9DB347E6F4');
        $this->addSql('ALTER TABLE se_user_roles DROP CONSTRAINT FK_E48BD9DBA1FA6DDA');
        $this->addSql('ALTER TABLE se_user_settings DROP CONSTRAINT FK_108FCAFA347E6F4');
        $this->addSql('ALTER TABLE se_users DROP CONSTRAINT FK_B10AC28E60E33F28');
        $this->addSql('ALTER TABLE se_users DROP CONSTRAINT FK_B10AC28EDBF11E1D');
        $this->addSql('ALTER TABLE se_users DROP CONSTRAINT FK_B10AC28E30D07CD5');
        $this->addSql('ALTER TABLE ta_tags DROP CONSTRAINT FK_B258E499DBF11E1D');
        $this->addSql('ALTER TABLE ta_tags DROP CONSTRAINT FK_B258E49930D07CD5');
        $this->addSql('ALTER TABLE tr_trash_item_translations DROP CONSTRAINT FK_8264DAF45C8D7CA');
        $this->addSql('ALTER TABLE tr_trash_items DROP CONSTRAINT FK_102989B64B64DCC');
        $this->addSql('ALTER TABLE we_analytics_domains DROP CONSTRAINT FK_F9323B6EEAC2E688');
        $this->addSql('ALTER TABLE we_analytics_domains DROP CONSTRAINT FK_F9323B6EA7A91E0B');
        $this->addSql('DROP TABLE ac_activities');
        $this->addSql('DROP TABLE at_target_group_conditions');
        $this->addSql('DROP TABLE at_target_group_rules');
        $this->addSql('DROP TABLE at_target_group_webspaces');
        $this->addSql('DROP TABLE at_target_groups');
        $this->addSql('DROP TABLE ca_categories');
        $this->addSql('DROP TABLE ca_category_meta');
        $this->addSql('DROP TABLE ca_category_translation_medias');
        $this->addSql('DROP TABLE ca_category_translations');
        $this->addSql('DROP TABLE ca_keywords');
        $this->addSql('DROP TABLE ca_category_translation_keywords');
        $this->addSql('DROP TABLE co_account_addresses');
        $this->addSql('DROP TABLE co_account_contacts');
        $this->addSql('DROP TABLE co_accounts');
        $this->addSql('DROP TABLE co_account_urls');
        $this->addSql('DROP TABLE co_account_phones');
        $this->addSql('DROP TABLE co_account_emails');
        $this->addSql('DROP TABLE co_account_notes');
        $this->addSql('DROP TABLE co_account_faxes');
        $this->addSql('DROP TABLE co_account_social_media_profiles');
        $this->addSql('DROP TABLE co_account_bank_accounts');
        $this->addSql('DROP TABLE co_account_categories');
        $this->addSql('DROP TABLE co_account_medias');
        $this->addSql('DROP TABLE co_account_tags');
        $this->addSql('DROP TABLE co_address_types');
        $this->addSql('DROP TABLE co_addresses');
        $this->addSql('DROP TABLE co_bank_account');
        $this->addSql('DROP TABLE co_contact_addresses');
        $this->addSql('DROP TABLE co_contact_locales');
        $this->addSql('DROP TABLE co_contact_titles');
        $this->addSql('DROP TABLE co_contacts');
        $this->addSql('DROP TABLE co_contact_urls');
        $this->addSql('DROP TABLE co_contact_notes');
        $this->addSql('DROP TABLE co_contact_emails');
        $this->addSql('DROP TABLE co_contact_phones');
        $this->addSql('DROP TABLE co_contact_faxes');
        $this->addSql('DROP TABLE co_contact_social_media_profiles');
        $this->addSql('DROP TABLE co_contact_bank_accounts');
        $this->addSql('DROP TABLE co_contact_medias');
        $this->addSql('DROP TABLE co_contact_categories');
        $this->addSql('DROP TABLE co_contact_tags');
        $this->addSql('DROP TABLE co_email_types');
        $this->addSql('DROP TABLE co_emails');
        $this->addSql('DROP TABLE co_fax_types');
        $this->addSql('DROP TABLE co_faxes');
        $this->addSql('DROP TABLE co_notes');
        $this->addSql('DROP TABLE co_phone_types');
        $this->addSql('DROP TABLE co_phones');
        $this->addSql('DROP TABLE co_positions');
        $this->addSql('DROP TABLE co_social_media_profile_types');
        $this->addSql('DROP TABLE co_social_media_profiles');
        $this->addSql('DROP TABLE co_url_types');
        $this->addSql('DROP TABLE co_urls');
        $this->addSql('DROP TABLE me_collection_meta');
        $this->addSql('DROP TABLE me_collection_types');
        $this->addSql('DROP TABLE me_collections');
        $this->addSql('DROP TABLE me_file_version_content_languages');
        $this->addSql('DROP TABLE me_file_version_meta');
        $this->addSql('DROP TABLE me_file_version_publish_languages');
        $this->addSql('DROP TABLE me_file_versions');
        $this->addSql('DROP TABLE me_file_version_tags');
        $this->addSql('DROP TABLE me_file_version_categories');
        $this->addSql('DROP TABLE me_file_version_target_groups');
        $this->addSql('DROP TABLE me_files');
        $this->addSql('DROP TABLE me_format_options');
        $this->addSql('DROP TABLE me_media');
        $this->addSql('DROP TABLE me_media_types');
        $this->addSql('DROP TABLE pr_preview_links');
        $this->addSql('DROP TABLE ro_routes');
        $this->addSql('DROP TABLE se_access_controls');
        $this->addSql('DROP TABLE se_groups');
        $this->addSql('DROP TABLE se_group_roles');
        $this->addSql('DROP TABLE se_permissions');
        $this->addSql('DROP TABLE se_role_settings');
        $this->addSql('DROP TABLE se_roles');
        $this->addSql('DROP TABLE se_security_types');
        $this->addSql('DROP TABLE se_user_groups');
        $this->addSql('DROP TABLE se_user_roles');
        $this->addSql('DROP TABLE se_user_settings');
        $this->addSql('DROP TABLE se_users');
        $this->addSql('DROP TABLE ta_tags');
        $this->addSql('DROP TABLE tr_trash_item_translations');
        $this->addSql('DROP TABLE tr_trash_items');
        $this->addSql('DROP TABLE we_analytics');
        $this->addSql('DROP TABLE we_analytics_domains');
        $this->addSql('DROP TABLE we_domains');
        $this->addSql('DROP TABLE phpcr_namespaces');
        $this->addSql('DROP TABLE phpcr_workspaces');
        $this->addSql('DROP TABLE phpcr_nodes');
        $this->addSql('DROP TABLE phpcr_internal_index_types');
        $this->addSql('DROP TABLE phpcr_binarydata');
        $this->addSql('DROP TABLE phpcr_nodes_references');
        $this->addSql('DROP TABLE phpcr_nodes_weakreferences');
        $this->addSql('DROP TABLE phpcr_type_nodes');
        $this->addSql('DROP TABLE phpcr_type_props');
        $this->addSql('DROP TABLE phpcr_type_childs');
    }
}
