<?php
/*
 * This file is part of the Sulu CMS.
 *
 * (c) MASSIVE ART WebServices GmbH
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Sulu\Bundle\CategoryBundle\Entity;

use Sulu\Bundle\CategoryBundle\Category\CategoryRepositoryInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository implements CategoryRepositoryInterface
{
    /**
     * Gets a category-entity by id
     * @param $id
     * @return mixed|null
     */
    public function findCategoryById($id)
    {
        try {
            $qb = $this->getCategoryQuery()->where('category.id = :categoryId');

            $query = $qb->getQuery();
            $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
            $query->setParameter('categoryId', $id);

            return $query->getSingleResult();

        } catch (NoResultException $ex) {
            return null;
        }
    }

    /**
     * Returns all categories. Can be filtered with parent and depth
     * @param number $parent the id of the parent to filter for
     * @param number $depth the depth-level to filter for
     * @param string|null $sortBy column name to sort the categories by
     * @param string|null $sortOrder sort order
     * @return mixed|null
     */
    public function findCategories($parent = null, $depth = null, $sortBy = null, $sortOrder = null)
    {
        try {
            $qb = $this->getCategoryQuery();

            if ($parent !== null) {
                $qb->andWhere('categoryParent.id = :parentId');
            }
            if ($depth !== null) {
                $qb->andWhere('category.depth = :depth');
            }

            if ($sortBy) {
                $sortOrder = ($sortOrder) ? $sortOrder : 'asc';
                $qb->addOrderBy('category.' . $sortBy, $sortOrder);
            }

            $query = $qb->getQuery();
            $query->setHint(Query::HINT_FORCE_PARTIAL_LOAD, true);
            if ($parent !== null) {
                $query->setParameter('parentId', $parent);
            }
            if ($depth !== null) {
                $query->setParameter('depth', $depth);
            }

            return $query->getResult();
        } catch (NoResultException $ex) {
            return null;
        }
    }

    /**
     * Finds the categories with the given ids
     * @param array $ids The ids to load
     * @return Category[]
     */
    public function findCategoryByIds(array $ids)
    {
        try {
            $qb = $this->getCategoryQuery();

            $qb->where($qb->expr()->in('category.id', ':ids'));
            $qb->setParameter('ids', $ids);

            return $qb->getQuery()->getResult();
        } catch (NoResultException $ex) {
            return null;
        }
    }

    /**
     * Returns the general part of the query
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getCategoryQuery()
    {
        $qb = $this->createQueryBuilder('category')
            ->leftJoin('category.meta', 'categoryMeta')
            ->leftJoin('category.translations', 'categoryTranslations')
            ->leftJoin('category.parent', 'categoryParent')
            ->leftJoin('category.children', 'categoryChildren')
            /*
            ->leftJoin('category.creator', 'creator')
            ->leftJoin('creator.contact', 'creatorContact')
            ->leftJoin('category.changer', 'changer')
            ->leftJoin('changer.contact', 'changerContact')
            */

            ->addSelect('category')
            ->addSelect('categoryMeta')
            ->addSelect('categoryTranslations')
            ->addSelect('categoryParent')
            ->addSelect('categoryChildren');
            /*
            ->addSelect('creator')
            ->addSelect('creatorContact')
            ->addSelect('changer')
            ->addSelect('changerContact')
            */

        return $qb;
    }
}
