<?php
use Sulu\Component\Portal\PortalCollection;
use Sulu\Component\Portal\Portal;

/**
 * PortalCollectionCache
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Portal component
 */
class PortalCollectionCache extends PortalCollection
{
    public function __construct()
    {
        $portal = new Portal();
        $portal->setName('Sulu');
        $portal->setKey('sulu');
        $this->add($portal);
        $portal = new Portal();
        $portal->setName('Sulu2');
        $portal->setKey('sulu2');
        $this->add($portal);
    }
}
