<?php
use Sulu\Component\Portal\PortalCollection;
use Sulu\Component\Portal\Portal;
use Sulu\Component\Portal\Language;
use Sulu\Component\Portal\Theme;
use Sulu\Component\Portal\Environment;
use Sulu\Component\Portal\Url;

/**
 * PortalCollectionCache
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Portal component
 */
class PortalCollectionCache extends PortalCollection
{
    public function __construct()
    {
    $portal = new Portal();

    $portal->setName('Sulu CMF');
    $portal->setKey('sulu_io');

            $language = new Language();
        $language->setCode('en');
        $language->setFallback('');
        $language->setMain('1');

        $portal->addLanguage($language);
            $language = new Language();
        $language->setCode('de');
        $language->setFallback('1');
        $language->setMain('');

        $portal->addLanguage($language);
    
    $theme = new Theme();
    $theme->setKey('sulu');
            $theme->addExcludedTemplate('overview');
    
    $portal->setTheme($theme);

            $environment = new Environment();
        $environment->setType('prod');

                    $url = new Url();
            $url->setMain(true);
            $url->setUrl('sulu.io');

            $environment->addUrl($url);
                    $url = new Url();
            $url->setMain(false);
            $url->setUrl('www.sulu.io');

            $environment->addUrl($url);
        
        $portal->addEnvironment($environment);
            $environment = new Environment();
        $environment->setType('dev');

                    $url = new Url();
            $url->setMain(true);
            $url->setUrl('sulu.lo');

            $environment->addUrl($url);
        
        $portal->addEnvironment($environment);
    
    $this->add($portal);

    }
}
