<?php

namespace Proxies\__CG__\Sulu\Bundle\TranslateBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Package extends \Sulu\Bundle\TranslateBundle\Entity\Package implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addCode(\Sulu\Bundle\TranslateBundle\Entity\Code $codes)
    {
        $this->__load();
        return parent::addCode($codes);
    }

    public function removeCode(\Sulu\Bundle\TranslateBundle\Entity\Code $codes)
    {
        $this->__load();
        return parent::removeCode($codes);
    }

    public function findCode($key)
    {
        $this->__load();
        return parent::findCode($key);
    }

    public function getCodes()
    {
        $this->__load();
        return parent::getCodes();
    }

    public function addLocation(\Sulu\Bundle\TranslateBundle\Entity\Location $locations)
    {
        $this->__load();
        return parent::addLocation($locations);
    }

    public function removeLocation(\Sulu\Bundle\TranslateBundle\Entity\Location $locations)
    {
        $this->__load();
        return parent::removeLocation($locations);
    }

    public function getLocations()
    {
        $this->__load();
        return parent::getLocations();
    }

    public function addCatalogue(\Sulu\Bundle\TranslateBundle\Entity\Catalogue $catalogues)
    {
        $this->__load();
        return parent::addCatalogue($catalogues);
    }

    public function removeCatalogue(\Sulu\Bundle\TranslateBundle\Entity\Catalogue $catalogues)
    {
        $this->__load();
        return parent::removeCatalogue($catalogues);
    }

    public function getCatalogues()
    {
        $this->__load();
        return parent::getCatalogues();
    }

    public function getLinks()
    {
        $this->__load();
        return parent::getLinks();
    }

    public function createSelfLink()
    {
        $this->__load();
        return parent::createSelfLink();
    }

    public function getApiPath()
    {
        $this->__load();
        return parent::getApiPath();
    }

    public function hasApiPath()
    {
        $this->__load();
        return parent::hasApiPath();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'id', 'catalogues', 'locations', 'codes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}