<?php

namespace Sulu\Bundle\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;

/**
 * AddressTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressTypeRepository extends EntityRepository
{
    public function findOneByName($name, $scrict = false)
    {
        try {
            if ($scrict === true) {
                $comparator = '=';
            } else {
                $comparator = 'LIKE';
                $name = '%' . $name . '%';
            }

            $qb = $this->createQueryBuilder('addressType')
                ->where('addressType.name ' . $comparator . ' :name')
                ->setParameter('name', $name);

            $query = $qb->getQuery();
            return $query->getSingleResult();
        } catch (NoResultException $ex) {
            return null;
        } catch (NonUniqueResultException $nure) {
            return null;
        }
    }
}
