<?php

/*
 * This file is part of Sulu.
 *
 * (c) Sulu GmbH
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Sulu\Component\Webspace\Tests\Unit\Manager;

use Sulu\Component\Localization\Localization;
use Sulu\Component\Webspace\Environment;
use Sulu\Component\Webspace\Manager\WebspaceCollection;
use Sulu\Component\Webspace\Navigation;
use Sulu\Component\Webspace\NavigationContext;
use Sulu\Component\Webspace\Portal;
use Sulu\Component\Webspace\PortalInformation;
use Sulu\Component\Webspace\Security;
use Sulu\Component\Webspace\Segment;
use Sulu\Component\Webspace\Url;
use Sulu\Component\Webspace\Webspace;

/**
 * WebspaceCollectionCache65db58eff00cf.
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Webspace component
 */
class WebspaceCollectionCache extends WebspaceCollection
{
    public function __construct()
    {
        $webspaceRefs = [];
        $portalRefs = [];
        $localizationRefs = [];
        $segmentRefs = [];
        $portalInformationRefs = [];

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('dan_io');
        $webspace->setName('Dan CMF');
        $security = new Security();
        $security->setSystem('dan_io');
        $security->setPermissionCheck(false);
        $webspace->setSecurity($security);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('us');
        $localization0->setShadow('auto');
        $localization0->setDefault(false);
        $localizationRefs['dan_io_en_us'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('at');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localizationRefs['dan_io_de_at'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $webspace->setTheme('dan');

        $webspace->addDefaultTemplate('page', 'default');
        $webspace->addDefaultTemplate('homepage', 'overview');
        $webspace->addDefaultTemplate('home', 'overview');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main', [
                        'title' => [
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                ],
                ]
        ));
        $navigation->addContext(new NavigationContext('footer', [
                        'title' => [
                        'de' => 'Unten',
                                'en' => 'Footer',
                ],
                ]
        ));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('short');

        // new portal
        $portal = new Portal();
        $portal->setName('Dan CMF AT');
        $portal->setKey('dancmf_at');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('us');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('at');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('dan.lo/de');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['dancmf_at'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['dan_io'] = $webspace;

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('massiveart');
        $webspace->setName('Massive Art');
        $security = new Security();
        $security->setSystem('massiveart');
        $security->setPermissionCheck(false);
        $webspace->setSecurity($security);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('us');
        $localization0->setShadow('auto');
        $localization0->setDefault(false);
        // parent id 0
        $localization1 = new Localization();
        $localization1->setLanguage('en');
        $localization1->setCountry('ca');
        $localization1->setShadow('');
        $localization1->setParent($localization0);
        $localization1->setDefault(false);

        $localizationRefs['massiveart_en_ca'] = $localization1;

        $localization0->addChild($localization1);

        $localizationRefs['massiveart_en_us'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('fr');
        $localization0->setCountry('ca');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localizationRefs['massiveart_fr_ca'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('');
        $localization0->setShadow('');
        $localization0->setDefault(false);
        $localizationRefs['massiveart_de'] = $localization0;
        $webspace->addLocalization($localization0);
        // add segment to webspace
        $segment = new Segment();
        $segment->setKey('w');
        $segment->setMetadata([
                        'title' => [
                        'en' => 'Winter',
                                'de' => 'Winter',
                ],
                ]
        );
        $segment->setDefault(true);
        $webspace->addSegment($segment);
        $segmentRefs['massiveart_w'] = $segment;

        // add segment to webspace
        $segment = new Segment();
        $segment->setKey('s');
        $segment->setMetadata([
                        'title' => [
                        'en' => 'Summer',
                                'de' => 'Sommer',
                ],
                ]
        );
        $segment->setDefault(false);
        $webspace->addSegment($segment);
        $segmentRefs['massiveart_s'] = $segment;

        // add theme
        $webspace->setTheme('massiveart');

        $webspace->addDefaultTemplate('page', 'default');
        $webspace->addDefaultTemplate('homepage', 'overview');
        $webspace->addDefaultTemplate('home', 'overview');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main', [
                        'title' => [
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                ],
                ]
        ));
        $navigation->addContext(new NavigationContext('footer', [
                        'title' => [
                        'de' => 'Unten',
                                'en' => 'Footer',
                ],
                ]
        ));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('tree_leaf_edit');

        // new portal
        $portal = new Portal();
        $portal->setName('Massive Art US');
        $portal->setKey('massiveart_us');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('us');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('ca');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('fr');
        $localization->setCountry('ca');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('{language}.massiveart.{country}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('massiveart.lo/{localization}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['massiveart_us'] = $portal;
        $webspace->addPortal($portal);

        // new portal
        $portal = new Portal();
        $portal->setName('Massive Art CA');
        $portal->setKey('massiveart_ca');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('ca');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('fr');
        $localization->setCountry('ca');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('{language}.massiveart.{country}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('www.massiveart.com');
        $url->setLanguage('en');
        $url->setCountry('ca');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(false);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('massiveart.lo/{localization}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['massiveart_ca'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['massiveart'] = $webspace;

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu_io');
        $webspace->setName('Sulu CMF');
        $security = new Security();
        $security->setSystem('sulu_io');
        $security->setPermissionCheck(false);
        $webspace->setSecurity($security);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('us');
        $localization0->setShadow('auto');
        $localization0->setDefault(false);
        $localizationRefs['sulu_io_en_us'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('at');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localizationRefs['sulu_io_de_at'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $webspace->setTheme('sulu');

        $webspace->addDefaultTemplate('page', 'default');
        $webspace->addDefaultTemplate('homepage', 'overview');
        $webspace->addDefaultTemplate('home', 'overview');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main', [
                        'title' => [
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                ],
                ]
        ));
        $navigation->addContext(new NavigationContext('footer', [
                        'title' => [
                        'de' => 'Unten',
                                'en' => 'Footer',
                ],
                ]
        ));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('tree_leaf_edit');

        // new portal
        $portal = new Portal();
        $portal->setName('Sulu CMF AT');
        $portal->setKey('sulucmf_at');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('us');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('at');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.at');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('www.sulu.at');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('sulu.at');
        $url->setMain(false);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('main');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(false);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.at');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('at.sulu.de');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(false);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulucmf_at'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu_io'] = $webspace;

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu_io_host_replacement');
        $webspace->setName('Sulu CMF');
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('at');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localizationRefs['sulu_io_host_replacement_de_at'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme

        $webspace->addDefaultTemplate('page', 'default');
        $webspace->addDefaultTemplate('homepage', 'overview');
        $webspace->addDefaultTemplate('home', 'overview');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main', [
                        'title' => [
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                ],
                ]
        ));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('tree_leaf_edit');

        // new portal
        $portal = new Portal();
        $portal->setName('Sulu CMF AT');
        $portal->setKey('sulucmf_at_host_replacement');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('at');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('test');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}/{localization}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulucmf_at_host_replacement'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu_io_host_replacement'] = $webspace;

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu_io_single_language');
        $webspace->setName('Sulu CMF');
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localizationRefs['sulu_io_single_language_en'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $webspace->setTheme('sulu');

        $webspace->addDefaultTemplate('page', 'default');
        $webspace->addDefaultTemplate('homepage', 'overview');
        $webspace->addDefaultTemplate('home', 'overview');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main', [
                        'title' => [
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                ],
                ]
        ));
        $navigation->addContext(new NavigationContext('footer', [
                        'title' => [
                        'de' => 'Unten',
                                'en' => 'Footer',
                ],
                ]
        ));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('short');

        // new portal
        $portal = new Portal();
        $portal->setName('Sulu CMF AT');
        $portal->setKey('sulucmf_singlelanguage_at');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu-single-language.at');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu-single-language.lo');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulucmf_singlelanguage_at'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu_io_single_language'] = $webspace;

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu_io_without_portal_localization');
        $webspace->setName('Sulu CMF');
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('us');
        $localization0->setShadow('auto');
        $localization0->setDefault(false);
        // parent id 0
        $localization1 = new Localization();
        $localization1->setLanguage('en');
        $localization1->setCountry('uk');
        $localization1->setShadow('');
        $localization1->setParent($localization0);
        $localization1->setDefault(false);

        $localizationRefs['sulu_io_without_portal_localization_en_uk'] = $localization1;

        $localization0->addChild($localization1);

        $localizationRefs['sulu_io_without_portal_localization_en_us'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('at');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localizationRefs['sulu_io_without_portal_localization_de_at'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $webspace->setTheme('sulu');

        $webspace->addDefaultTemplate('page', 'default');
        $webspace->addDefaultTemplate('homepage', 'overview');
        $webspace->addDefaultTemplate('home', 'overview');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main', [
                        'title' => [
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                ],
                ]
        ));
        $navigation->addContext(new NavigationContext('footer', [
                        'title' => [
                        'de' => 'Unten',
                                'en' => 'Footer',
                ],
                ]
        ));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('short');

        // new portal
        $portal = new Portal();
        $portal->setName('Sulu CMF AT');
        $portal->setKey('sulucmf_withoutportallocalizations_at');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('us');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('uk');
        $localization->setDefault(false);
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('at');
        $localization->setDefault(true);
        $portal->addLocalization($localization);

        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu-without.at');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu-without.lo');
        $url->setLanguage('de');
        $url->setCountry('at');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulucmf_withoutportallocalizations_at'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu_io_without_portal_localization'] = $webspace;

        $portalInformationRefs['dev']['sulu-single-language.lo'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io_single_language'],
            $portalRefs['sulucmf_singlelanguage_at'],
            $localizationRefs['sulu_io_single_language_en'],
            'sulu-single-language.lo',
            null,
            null,
            true,
            'sulu-single-language.lo',
            10
        );

        $portalInformationRefs['dev']['massiveart.lo/en-us'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_us'],
            $localizationRefs['massiveart_en_us'],
            'massiveart.lo/en-us',
            null,
            null,
            true,
            'massiveart.lo/{localization}',
            10
        );

        $portalInformationRefs['dev']['massiveart.lo/en-ca'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_ca'],
            $localizationRefs['massiveart_en_ca'],
            'massiveart.lo/en-ca',
            null,
            null,
            true,
            'massiveart.lo/{localization}',
            10
        );

        $portalInformationRefs['dev']['massiveart.lo/fr-ca'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_ca'],
            $localizationRefs['massiveart_fr_ca'],
            'massiveart.lo/fr-ca',
            null,
            null,
            true,
            'massiveart.lo/{localization}',
            10
        );

        $portalInformationRefs['dev']['massiveart.lo/de'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_us'],
            $localizationRefs['massiveart_de'],
            'massiveart.lo/de',
            null,
            null,
            true,
            'massiveart.lo/{localization}',
            10
        );

        $portalInformationRefs['dev']['sulu-without.lo'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io_without_portal_localization'],
            $portalRefs['sulucmf_withoutportallocalizations_at'],
            $localizationRefs['sulu_io_without_portal_localization_de_at'],
            'sulu-without.lo',
            null,
            null,
            true,
            'sulu-without.lo',
            10
        );

        $portalInformationRefs['dev']['massiveart.lo'] = new PortalInformation(
            2,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_us'],
            null,
            'massiveart.lo',
            null,
            'massiveart.lo/{localization}',
            false,
            'massiveart.lo/{localization}',
            9
        );

        $portalInformationRefs['dev']['dan.lo/de'] = new PortalInformation(
            1,
            $webspaceRefs['dan_io'],
            $portalRefs['dancmf_at'],
            $localizationRefs['dan_io_de_at'],
            'dan.lo/de',
            null,
            null,
            true,
            'dan.lo/de',
            10
        );

        $portalInformationRefs['dev']['sulu.lo'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.lo',
            null,
            null,
            true,
            'sulu.lo',
            10
        );

        $portalInformationRefs['prod']['sulu-single-language.at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io_single_language'],
            $portalRefs['sulucmf_singlelanguage_at'],
            $localizationRefs['sulu_io_single_language_en'],
            'sulu-single-language.at',
            null,
            null,
            true,
            'sulu-single-language.at',
            10
        );

        $portalInformationRefs['prod']['www.massiveart.com'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_ca'],
            $localizationRefs['massiveart_en_ca'],
            'www.massiveart.com',
            null,
            null,
            false,
            'www.massiveart.com',
            10
        );

        $portalInformationRefs['prod']['en.massiveart.us'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_us'],
            $localizationRefs['massiveart_en_us'],
            'en.massiveart.us',
            null,
            null,
            true,
            '{language}.massiveart.{country}',
            10
        );

        $portalInformationRefs['prod']['en.massiveart.ca'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_ca'],
            $localizationRefs['massiveart_en_ca'],
            'en.massiveart.ca',
            null,
            null,
            true,
            '{language}.massiveart.{country}',
            10
        );

        $portalInformationRefs['prod']['fr.massiveart.ca'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_ca'],
            $localizationRefs['massiveart_fr_ca'],
            'fr.massiveart.ca',
            null,
            null,
            true,
            '{language}.massiveart.{country}',
            10
        );

        $portalInformationRefs['prod']['sulu-without.at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io_without_portal_localization'],
            $portalRefs['sulucmf_withoutportallocalizations_at'],
            $localizationRefs['sulu_io_without_portal_localization_de_at'],
            'sulu-without.at',
            null,
            null,
            true,
            'sulu-without.at',
            10
        );

        $portalInformationRefs['prod']['de.massiveart.'] = new PortalInformation(
            1,
            $webspaceRefs['massiveart'],
            $portalRefs['massiveart_us'],
            $localizationRefs['massiveart_de'],
            'de.massiveart.',
            null,
            null,
            true,
            '{language}.massiveart.{country}',
            10
        );

        $portalInformationRefs['prod']['www.sulu.at'] = new PortalInformation(
            3,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            null,
            'www.sulu.at',
            null,
            'sulu.at',
            false,
            'www.sulu.at',
            9
        );

        $portalInformationRefs['prod']['sulu.at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.at',
            null,
            null,
            true,
            'sulu.at',
            10
        );

        $portalInformationRefs['test']['{host}/de-at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io_host_replacement'],
            $portalRefs['sulucmf_at_host_replacement'],
            $localizationRefs['sulu_io_host_replacement_de_at'],
            '{host}/de-at',
            null,
            null,
            true,
            '{host}/{localization}',
            5
        );

        $portalInformationRefs['test']['www.sulu.at'] = new PortalInformation(
            3,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            null,
            'www.sulu.at',
            null,
            'sulu.at',
            false,
            'www.sulu.at',
            9
        );

        $portalInformationRefs['test']['sulu.at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.at',
            null,
            null,
            true,
            'sulu.at',
            10
        );

        $portalInformationRefs['test']['{host}'] = new PortalInformation(
            2,
            $webspaceRefs['sulu_io_host_replacement'],
            $portalRefs['sulucmf_at_host_replacement'],
            null,
            '{host}',
            null,
            '{host}/{localization}',
            false,
            '{host}/{localization}',
            4
        );

        $portalInformationRefs['main']['at.sulu.de'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'at.sulu.de',
            null,
            null,
            false,
            'at.sulu.de',
            10
        );

        $portalInformationRefs['main']['sulu.lo'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.lo',
            null,
            null,
            false,
            'sulu.lo',
            10
        );

        $portalInformationRefs['main']['sulu.at'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulucmf_at'],
            $localizationRefs['sulu_io_de_at'],
            'sulu.at',
            null,
            null,
            true,
            'sulu.at',
            10
        );

        parent::__construct(
            $webspaceRefs,
            $portalRefs,
            $portalInformationRefs
        );
    }
}
