sulu_media.redirect:
    path: /redirect/media/{id}
    controller: sulu_media.media_redirect_controller::redirectAction

sulu_media.media.download_admin:
    path: "%sulu_media.media_manager.media_download_path_admin%"
    controller: sulu_media.media_stream_controller::downloadAction
    defaults:
        _requestAnalyzer: false
    requirements:
        id: "\\d+"
